<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\paskalON.Common\paskalON.Domains\paskalON.Domains.csproj" />
    <ProjectReference Include="..\..\paskalON.Communication\paskalON.Protocols.C37118\paskalON.Protocols.C37118.csproj" />
    <ProjectReference Include="..\..\paskalON.Communication\paskalON.Protocols.Modbus\paskalON.Protocols.Modbus.csproj" />
    <ProjectReference Include="..\paskalON.Devices.Domain.Configs\paskalON.Devices.Domain.Configs.csproj" />
    <ProjectReference Include="..\paskalON.Devices.Domain\paskalON.Devices.Domain.csproj" />
  </ItemGroup>

</Project>
