// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using paskalON.PowerControls.Infrastructure.Storage;

#nullable disable

namespace paskalON.PowerControls.Infrastructure.Storage.Migrations
{
    [DbContext(typeof(PowerControlContext))]
    [Migration("20260923193328_v_0_1")]
    partial class v_0_1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence("DomainBaseSequence");

            modelBuilder.Entity("paskalON.Domains.DomainBase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValueSql("nextval('\"DomainBaseSequence\"')");

                    NpgsqlPropertyBuilderExtensions.UseSequence(b.Property<int>("Id"));

                    b.Property<string>("ChangedBy")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<DateTimeOffset>("ChangedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable((string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("paskalON.Domains.History", b =>
                {
                    b.Property<string>("MigrationId")
                        .HasColumnType("text");

                    b.Property<string>("ProductVersion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MigrationId");

                    b.ToTable("__EFMigrationsHistory", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("paskalON.Domains.ConfigurationBase", b =>
                {
                    b.HasBaseType("paskalON.Domains.DomainBase");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(800)
                        .HasColumnType("character varying(800)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.ToTable((string)null);
                });

            modelBuilder.Entity("paskalON.Domains.NameBase", b =>
                {
                    b.HasBaseType("paskalON.Domains.DomainBase");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable((string)null);
                });

            modelBuilder.Entity("paskalON.PowerControls.Domain.Configs.SystemConfig", b =>
                {
                    b.HasBaseType("paskalON.Domains.DomainBase");

                    b.Property<int>("MetricsIntervalMilliseconds")
                        .HasColumnType("integer");

                    b.Property<int>("StartupDelayForDevices")
                        .HasColumnType("integer");

                    b.Property<string>("SubscriberTopicAuxiliaryPowerMeterCore")
                        .HasColumnType("text");

                    b.Property<string>("SubscriberTopicAuxiliaryPowerMeterDetail")
                        .HasColumnType("text");

                    b.Property<string>("SubscriberTopicBatteryBankCore")
                        .HasColumnType("text");

                    b.Property<string>("SubscriberTopicBatteryBankDetail")
                        .HasColumnType("text");

                    b.Property<string>("SubscriberTopicCircuitPowerMeterCore")
                        .HasColumnType("text");

                    b.Property<string>("SubscriberTopicCircuitPowerMeterDetail")
                        .HasColumnType("text");

                    b.Property<string>("SubscriberTopicExternalPowerMeterCore")
                        .HasColumnType("text");

                    b.Property<string>("SubscriberTopicExternalPowerMeterDetail")
                        .HasColumnType("text");

                    b.Property<string>("SubscriberTopicPcsCore")
                        .HasColumnType("text");

                    b.Property<string>("SubscriberTopicPcsDetail")
                        .HasColumnType("text");

                    b.Property<string>("SubscriberTopicSolarPanelCore")
                        .HasColumnType("text");

                    b.Property<string>("SubscriberTopicSolarPanelDetail")
                        .HasColumnType("text");

                    b.Property<string>("SubscriberTopicSystemPowerMeterCore")
                        .HasColumnType("text");

                    b.Property<string>("SubscriberTopicSystemPowerMeterDetail")
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.ToTable("SystemConfig");
                });

            modelBuilder.Entity("paskalON.PowerControls.Domain.Configs.Configuration", b =>
                {
                    b.HasBaseType("paskalON.Domains.ConfigurationBase");

                    b.ToTable("Configuration");
                });

            modelBuilder.Entity("paskalON.ConstraintEngine.Domain.Configs.ConstraintBaseConfig", b =>
                {
                    b.HasBaseType("paskalON.Domains.NameBase");

                    b.Property<int?>("PowerControlBaseConfigId")
                        .HasColumnType("integer");

                    b.HasIndex("PowerControlBaseConfigId");

                    b.ToTable((string)null);
                });

            modelBuilder.Entity("paskalON.PowerControls.Domain.Configs.PowerControlBaseConfig", b =>
                {
                    b.HasBaseType("paskalON.Domains.NameBase");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.ToTable((string)null);
                });

            modelBuilder.Entity("paskalON.ConstraintEngine.Domain.Configs.Ders.DerUnitPowerConstraintConfig", b =>
                {
                    b.HasBaseType("paskalON.ConstraintEngine.Domain.Configs.ConstraintBaseConfig");

                    b.Property<double?>("MaximumActivePowerWatt")
                        .HasColumnType("double precision");

                    b.Property<double?>("MaximumReactivePowerVars")
                        .HasColumnType("double precision");

                    b.Property<double?>("MinimumActivePowerWatt")
                        .HasColumnType("double precision");

                    b.Property<double?>("MinimumReactivePowerVars")
                        .HasColumnType("double precision");

                    b.ToTable("DerUnitPowerConstraintConfig");
                });

            modelBuilder.Entity("paskalON.ConstraintEngine.Domain.Configs.Ders.DerUnitRampConstraintConfig", b =>
                {
                    b.HasBaseType("paskalON.ConstraintEngine.Domain.Configs.ConstraintBaseConfig");

                    b.Property<double>("MaximumActivePowerWattRampRatePerSecond")
                        .HasColumnType("double precision");

                    b.Property<double>("MaximumReactivePowerVarsRampRatePerSecond")
                        .HasColumnType("double precision");

                    b.ToTable("DerUnitRampConstraintConfig");
                });

            modelBuilder.Entity("paskalON.ConstraintEngine.Domain.Configs.Systems.SystemPowerConstraintConfig", b =>
                {
                    b.HasBaseType("paskalON.ConstraintEngine.Domain.Configs.ConstraintBaseConfig");

                    b.Property<bool>("DeratePerUnitInMaintenance")
                        .HasColumnType("boolean");

                    b.Property<bool>("DeratePerUnitStopped")
                        .HasColumnType("boolean");

                    b.Property<double?>("MaximumActivePowerWatt")
                        .HasColumnType("double precision");

                    b.Property<double?>("MaximumReactivePowerVars")
                        .HasColumnType("double precision");

                    b.Property<double?>("MinimumActivePowerWatt")
                        .HasColumnType("double precision");

                    b.Property<double?>("MinimumReactivePowerVars")
                        .HasColumnType("double precision");

                    b.ToTable("SystemPowerConstraintConfig");
                });

            modelBuilder.Entity("paskalON.ConstraintEngine.Domain.Configs.Systems.SystemRampConstraintConfig", b =>
                {
                    b.HasBaseType("paskalON.ConstraintEngine.Domain.Configs.ConstraintBaseConfig");

                    b.Property<double>("MaximumActivePowerWattRampRatePerSecond")
                        .HasColumnType("double precision");

                    b.Property<double>("MaximumReactivePowerVarsRampRatePerSecond")
                        .HasColumnType("double precision");

                    b.ToTable("SystemRampConstraintConfig");
                });

            modelBuilder.Entity("paskalON.PowerControls.Domain.Configs.Ders.DerUnitEnergyStoragePowerControlConfig", b =>
                {
                    b.HasBaseType("paskalON.PowerControls.Domain.Configs.PowerControlBaseConfig");

                    b.Property<string>("DerUnitName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<int>("DistributionStrategyType")
                        .HasColumnType("integer");

                    b.ToTable("DerUnitEnergyStoragePowerControlConfig");
                });

            modelBuilder.Entity("paskalON.PowerControls.Domain.Configs.Ders.DerUnitPowerControlConfig", b =>
                {
                    b.HasBaseType("paskalON.PowerControls.Domain.Configs.PowerControlBaseConfig");

                    b.Property<string>("DerUnitName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<int>("DistributionStrategyType")
                        .HasColumnType("integer");

                    b.Property<int?>("Priority")
                        .HasColumnType("integer");

                    b.Property<double?>("Weight")
                        .HasColumnType("double precision");

                    b.ToTable("DerUnitPowerControlConfig");
                });

            modelBuilder.Entity("paskalON.PowerControls.Domain.Configs.Systems.SystemPowerControlConfig", b =>
                {
                    b.HasBaseType("paskalON.PowerControls.Domain.Configs.PowerControlBaseConfig");

                    b.ToTable("SystemPowerControlConfig");
                });

            modelBuilder.Entity("paskalON.ConstraintEngine.Domain.Configs.ConstraintBaseConfig", b =>
                {
                    b.HasOne("paskalON.PowerControls.Domain.Configs.PowerControlBaseConfig", null)
                        .WithMany("Constraints")
                        .HasForeignKey("PowerControlBaseConfigId");
                });

            modelBuilder.Entity("paskalON.PowerControls.Domain.Configs.PowerControlBaseConfig", b =>
                {
                    b.Navigation("Constraints");
                });
#pragma warning restore 612, 618
        }
    }
}
