#------------------------------------------------------------------------------
# Variables
#------------------------------------------------------------------------------
@paskalON.PowerControls.Service_HostAddress = http://localhost:45010

#------------------------------------------------------------------------------
# Version controller
#------------------------------------------------------------------------------
GET {{paskalON.PowerControls.Service_HostAddress}}/api/v1/version/
Accept: application/json

###
