apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://paskalon.influxdb:8181
    uid: influxdbdatasource
    jsonData:
      version: SQL
      dbName: ppc
      httpMode: POST
      insecureGrpc: true
    # Make it editable for DEV/TST environments
    editable: true

  - name: Loki
    type: loki
    access: proxy
    url: http://paskalon.loki:3100
    basicAuth: false
    uid: lokidatasource
    version: 1
    # Make it editable for DEV/TST environments
    editable: true
