services:
  paskalon.devices.service:
    image: ${DOCKER_REGISTRY-}paskalondevicesservice
    build:
      context: .
      dockerfile: paskalON.Devices.Service/Dockerfile
    ports:
      - 45000:8080
