<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\paskalON.DeviceService\paskalON.Devices.Application\paskalON.Devices.Application.csproj" />
    <ProjectReference Include="..\paskalON.DeviceSimulator.Equipments\paskalON.DeviceSimulator.Equipments.csproj" />
  </ItemGroup>

</Project>
