// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using paskalON.OperatingModes.Infrastructure.Storage;

#nullable disable

namespace paskalON.OperatingModes.Infrastructure.Storage.Migrations
{
    [DbContext(typeof(OperatingModeContext))]
    [Migration("20261001184357_v_0_1")]
    partial class v_0_1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence("DomainBaseSequence");

            modelBuilder.Entity("paskalON.Domains.DomainBase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValueSql("nextval('\"DomainBaseSequence\"')");

                    NpgsqlPropertyBuilderExtensions.UseSequence(b.Property<int>("Id"));

                    b.Property<string>("ChangedBy")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<DateTimeOffset>("ChangedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable((string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("paskalON.Domains.History", b =>
                {
                    b.Property<string>("MigrationId")
                        .HasColumnType("text");

                    b.Property<string>("ProductVersion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MigrationId");

                    b.ToTable("__EFMigrationsHistory", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("paskalON.Domains.ConfigurationBase", b =>
                {
                    b.HasBaseType("paskalON.Domains.DomainBase");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(800)
                        .HasColumnType("character varying(800)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.ToTable((string)null);
                });

            modelBuilder.Entity("paskalON.Domains.NameBase", b =>
                {
                    b.HasBaseType("paskalON.Domains.DomainBase");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable((string)null);
                });

            modelBuilder.Entity("paskalON.OperatingModes.Domain.Configs.Curves.CurvePointConfig", b =>
                {
                    b.HasBaseType("paskalON.Domains.DomainBase");

                    b.Property<int>("CurveBaseConfigId")
                        .HasColumnType("integer");

                    b.Property<double>("X")
                        .HasColumnType("double precision");

                    b.Property<double>("Y")
                        .HasColumnType("double precision");

                    b.HasIndex("CurveBaseConfigId");

                    b.ToTable("CurvePointConfig");
                });

            modelBuilder.Entity("paskalON.OperatingModes.Domain.Configs.Ramps.RampBaseConfig", b =>
                {
                    b.HasBaseType("paskalON.Domains.DomainBase");

                    b.Property<int>("RampTimeSeconds")
                        .HasColumnType("integer");

                    b.ToTable((string)null);
                });

            modelBuilder.Entity("paskalON.OperatingModes.Domain.Configs.SystemConfig", b =>
                {
                    b.HasBaseType("paskalON.Domains.DomainBase");

                    b.Property<int>("MetricsIntervalMilliseconds")
                        .HasColumnType("integer");

                    b.Property<double>("NameplateMaximumActivePowerWatt")
                        .HasColumnType("double precision");

                    b.Property<double>("NameplateMaximumCurrent")
                        .HasColumnType("double precision");

                    b.Property<double>("NameplateMaximumReactivePowerVars")
                        .HasColumnType("double precision");

                    b.Property<double>("NameplateMaximumVoltage")
                        .HasColumnType("double precision");

                    b.Property<double>("NameplateMinimumActivePowerWatt")
                        .HasColumnType("double precision");

                    b.Property<double>("NameplateMinimumCurrent")
                        .HasColumnType("double precision");

                    b.Property<double>("NameplateMinimumReactivePowerVars")
                        .HasColumnType("double precision");

                    b.Property<double>("NameplateMinimumVoltage")
                        .HasColumnType("double precision");

                    b.Property<double>("ReferenceFrequency")
                        .HasColumnType("double precision");

                    b.Property<double>("ReferenceVoltage")
                        .HasColumnType("double precision");

                    b.Property<int>("StartupDelay")
                        .HasColumnType("integer");

                    b.Property<string>("SubscriberTopicAuxiliaryPowerMeterCore")
                        .HasColumnType("text");

                    b.Property<string>("SubscriberTopicAuxiliaryPowerMeterDetail")
                        .HasColumnType("text");

                    b.Property<string>("SubscriberTopicBatteryBankCore")
                        .HasColumnType("text");

                    b.Property<string>("SubscriberTopicBatteryBankDetail")
                        .HasColumnType("text");

                    b.Property<string>("SubscriberTopicCircuitPowerMeterCore")
                        .HasColumnType("text");

                    b.Property<string>("SubscriberTopicCircuitPowerMeterDetail")
                        .HasColumnType("text");

                    b.Property<string>("SubscriberTopicExternalPowerMeterCore")
                        .HasColumnType("text");

                    b.Property<string>("SubscriberTopicExternalPowerMeterDetail")
                        .HasColumnType("text");

                    b.Property<string>("SubscriberTopicPcsCore")
                        .HasColumnType("text");

                    b.Property<string>("SubscriberTopicPcsDetail")
                        .HasColumnType("text");

                    b.Property<string>("SubscriberTopicSolarPanelCore")
                        .HasColumnType("text");

                    b.Property<string>("SubscriberTopicSolarPanelDetail")
                        .HasColumnType("text");

                    b.Property<string>("SubscriberTopicSystemPowerMeterCore")
                        .HasColumnType("text");

                    b.Property<string>("SubscriberTopicSystemPowerMeterDetail")
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.ToTable("SystemConfig");
                });

            modelBuilder.Entity("paskalON.OperatingModes.Domain.Configs.Configuration", b =>
                {
                    b.HasBaseType("paskalON.Domains.ConfigurationBase");

                    b.ToTable("Configuration");
                });

            modelBuilder.Entity("paskalON.OperatingModes.Domain.Configs.Curves.CurveBaseConfig", b =>
                {
                    b.HasBaseType("paskalON.Domains.NameBase");

                    b.Property<int>("RampDownTimeSeconds")
                        .HasColumnType("integer");

                    b.Property<int>("RampUpTimeSeconds")
                        .HasColumnType("integer");

                    b.Property<bool>("UseRamp")
                        .HasColumnType("boolean");

                    b.Property<int>("XUnit")
                        .HasColumnType("integer");

                    b.Property<int>("YUnit")
                        .HasColumnType("integer");

                    b.ToTable((string)null);
                });

            modelBuilder.Entity("paskalON.OperatingModes.Domain.Configs.OperatingModeBaseConfig", b =>
                {
                    b.HasBaseType("paskalON.Domains.NameBase");

                    b.Property<int?>("CurveConfigId")
                        .HasColumnType("integer");

                    b.Property<double>("DeadbandAvailable")
                        .HasColumnType("double precision");

                    b.Property<double>("DeadbandSetpoint")
                        .HasColumnType("double precision");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<double?>("MaximumActivePowerLimitWatt")
                        .HasColumnType("double precision");

                    b.Property<double?>("MaximumReactivePowerLimitVars")
                        .HasColumnType("double precision");

                    b.Property<int>("MetricsFactorClass1")
                        .HasColumnType("integer");

                    b.Property<int>("MetricsFactorClass2")
                        .HasColumnType("integer");

                    b.Property<int>("MetricsFactorClass3")
                        .HasColumnType("integer");

                    b.Property<int>("MetricsFactorClass4")
                        .HasColumnType("integer");

                    b.Property<long>("MetricsIntervalMilliseconds")
                        .HasColumnType("bigint");

                    b.Property<double?>("MinimumActivePowerLimitWatt")
                        .HasColumnType("double precision");

                    b.Property<double?>("MinimumReactivePowerLimitVars")
                        .HasColumnType("double precision");

                    b.Property<int>("RampConfigId")
                        .HasColumnType("integer");

                    b.Property<int>("TimeoutSeconds")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasIndex("CurveConfigId");

                    b.HasIndex("RampConfigId");

                    b.ToTable((string)null);
                });

            modelBuilder.Entity("paskalON.OperatingModes.Domain.Configs.Ramps.RampRateConfig", b =>
                {
                    b.HasBaseType("paskalON.OperatingModes.Domain.Configs.Ramps.RampBaseConfig");

                    b.Property<double>("RampDownRatePerSecond")
                        .HasColumnType("double precision");

                    b.Property<double>("RampUpRatePerSecond")
                        .HasColumnType("double precision");

                    b.ToTable("RampRateConfig");
                });

            modelBuilder.Entity("paskalON.OperatingModes.Domain.Configs.Ramps.RampRatePercentageConfig", b =>
                {
                    b.HasBaseType("paskalON.OperatingModes.Domain.Configs.Ramps.RampBaseConfig");

                    b.Property<double>("RampDownRatePercentPerSecond")
                        .HasColumnType("double precision");

                    b.Property<int>("RampRatePrecision")
                        .HasColumnType("integer");

                    b.Property<double>("RampUpRatePercentPerSecond")
                        .HasColumnType("double precision");

                    b.ToTable("RampRatePercentageConfig");
                });

            modelBuilder.Entity("paskalON.OperatingModes.Domain.Configs.Ramps.RampTimeConfig", b =>
                {
                    b.HasBaseType("paskalON.OperatingModes.Domain.Configs.Ramps.RampBaseConfig");

                    b.Property<int>("RampDownTimeSeconds")
                        .HasColumnType("integer");

                    b.Property<int>("RampUpTimeSeconds")
                        .HasColumnType("integer");

                    b.ToTable("RampTimeConfig");
                });

            modelBuilder.Entity("paskalON.OperatingModes.Domain.Configs.Ramps.RampTimeConstantConfig", b =>
                {
                    b.HasBaseType("paskalON.OperatingModes.Domain.Configs.Ramps.RampBaseConfig");

                    b.Property<int>("RampDownTimeConstantSeconds")
                        .HasColumnType("integer");

                    b.Property<int>("RampUpTimeConstantSeconds")
                        .HasColumnType("integer");

                    b.Property<int>("TuningValue")
                        .HasColumnType("integer");

                    b.ToTable("RampTimeConstantConfig");
                });

            modelBuilder.Entity("paskalON.OperatingModes.Domain.Configs.Curves.FrequencyWattCurveConfig", b =>
                {
                    b.HasBaseType("paskalON.OperatingModes.Domain.Configs.Curves.CurveBaseConfig");

                    b.ToTable("FrequencyWattCurveConfig");
                });

            modelBuilder.Entity("paskalON.OperatingModes.Domain.Configs.Curves.VoltVarCurveConfig", b =>
                {
                    b.HasBaseType("paskalON.OperatingModes.Domain.Configs.Curves.CurveBaseConfig");

                    b.ToTable("VoltVarCurveConfig");
                });

            modelBuilder.Entity("paskalON.OperatingModes.Domain.Configs.Curves.VoltWattCurveConfig", b =>
                {
                    b.HasBaseType("paskalON.OperatingModes.Domain.Configs.Curves.CurveBaseConfig");

                    b.ToTable("VoltWattCurveConfig");
                });

            modelBuilder.Entity("paskalON.OperatingModes.Domain.Configs.ClosedModes.EnergyStorages.ChargeDischargeModeConfig", b =>
                {
                    b.HasBaseType("paskalON.OperatingModes.Domain.Configs.OperatingModeBaseConfig");

                    b.Property<double>("DeadbandError")
                        .HasColumnType("double precision");

                    b.Property<double>("MaximumStorageReserveDeadband")
                        .HasColumnType("double precision");

                    b.Property<double>("MinimumStorageReserveDeadband")
                        .HasColumnType("double precision");

                    b.ToTable("ChargeDischargeModeConfig");
                });

            modelBuilder.Entity("paskalON.OperatingModes.Domain.Configs.ClosedModes.EnergyStorages.CoordinatedChargeDischargeModeConfig", b =>
                {
                    b.HasBaseType("paskalON.OperatingModes.Domain.Configs.OperatingModeBaseConfig");

                    b.Property<double>("DeadbandError")
                        .HasColumnType("double precision");

                    b.Property<double>("MaximumStorageReserveDeadband")
                        .HasColumnType("double precision");

                    b.Property<double>("MinimumStorageReserveDeadband")
                        .HasColumnType("double precision");

                    b.ToTable("CoordinatedChargeDischargeModeConfig");
                });

            modelBuilder.Entity("paskalON.OperatingModes.Domain.Configs.ClosedModes.FrequencyActives.ActivePowerModeConfig", b =>
                {
                    b.HasBaseType("paskalON.OperatingModes.Domain.Configs.OperatingModeBaseConfig");

                    b.Property<double>("DeadbandError")
                        .HasColumnType("double precision");

                    b.Property<double>("ProportionalGain")
                        .HasColumnType("double precision");

                    b.ToTable("ActivePowerModeConfig");
                });

            modelBuilder.Entity("paskalON.OperatingModes.Domain.Configs.ClosedModes.FrequencyActives.FrequencyDroopModeConfig", b =>
                {
                    b.HasBaseType("paskalON.OperatingModes.Domain.Configs.OperatingModeBaseConfig");

                    b.Property<double>("DeadbandError")
                        .HasColumnType("double precision");

                    b.Property<int>("HealthyResponseDelayMilliseconds")
                        .HasColumnType("integer");

                    b.ToTable("FrequencyDroopModeConfig");
                });

            modelBuilder.Entity("paskalON.OperatingModes.Domain.Configs.ClosedModes.FrequencyActives.FrequencyWattModeConfig", b =>
                {
                    b.HasBaseType("paskalON.OperatingModes.Domain.Configs.OperatingModeBaseConfig");

                    b.Property<double>("DeadbandError")
                        .HasColumnType("double precision");

                    b.Property<int>("HealthyResponseDelayMilliseconds")
                        .HasColumnType("integer");

                    b.ToTable("FrequencyWattModeConfig");
                });

            modelBuilder.Entity("paskalON.OperatingModes.Domain.Configs.ClosedModes.FrequencyActives.MaximumActivePowerLimitModeConfig", b =>
                {
                    b.HasBaseType("paskalON.OperatingModes.Domain.Configs.OperatingModeBaseConfig");

                    b.Property<double>("DeadbandError")
                        .HasColumnType("double precision");

                    b.Property<double?>("MaximumActivePowerLimitWatts")
                        .HasColumnType("double precision");

                    b.ToTable("MaximumActivePowerLimitModeConfig");
                });

            modelBuilder.Entity("paskalON.OperatingModes.Domain.Configs.ClosedModes.MaintenanceSocModeConfig", b =>
                {
                    b.HasBaseType("paskalON.OperatingModes.Domain.Configs.OperatingModeBaseConfig");

                    b.Property<double>("DeadbandError")
                        .HasColumnType("double precision");

                    b.Property<double>("TargetStateOfCharge")
                        .HasColumnType("double precision");

                    b.Property<bool>("UseTargetStateOfCharge")
                        .HasColumnType("boolean");

                    b.ToTable("MaintenanceSocModeConfig");
                });

            modelBuilder.Entity("paskalON.OperatingModes.Domain.Configs.ClosedModes.VoltageActives.VoltageWattDroopModeConfig", b =>
                {
                    b.HasBaseType("paskalON.OperatingModes.Domain.Configs.OperatingModeBaseConfig");

                    b.Property<double>("DeadbandError")
                        .HasColumnType("double precision");

                    b.ToTable("VoltageWattDroopModeConfig");
                });

            modelBuilder.Entity("paskalON.OperatingModes.Domain.Configs.ClosedModes.VoltageReactives.PowerFactorModeConfig", b =>
                {
                    b.HasBaseType("paskalON.OperatingModes.Domain.Configs.OperatingModeBaseConfig");

                    b.Property<double>("DeadbandError")
                        .HasColumnType("double precision");

                    b.Property<float>("PowerFactorTarget")
                        .HasColumnType("real");

                    b.ToTable("PowerFactorModeConfig");
                });

            modelBuilder.Entity("paskalON.OperatingModes.Domain.Configs.ClosedModes.VoltageReactives.ReactivePowerModeConfig", b =>
                {
                    b.HasBaseType("paskalON.OperatingModes.Domain.Configs.OperatingModeBaseConfig");

                    b.Property<double>("DeadbandError")
                        .HasColumnType("double precision");

                    b.Property<double>("ProportionalGain")
                        .HasColumnType("double precision");

                    b.ToTable("ReactivePowerModeConfig");
                });

            modelBuilder.Entity("paskalON.OperatingModes.Domain.Configs.ClosedModes.VoltageReactives.VoltageModeConfig", b =>
                {
                    b.HasBaseType("paskalON.OperatingModes.Domain.Configs.OperatingModeBaseConfig");

                    b.Property<double>("DeadbandError")
                        .HasColumnType("double precision");

                    b.ToTable("VoltageModeConfig");
                });

            modelBuilder.Entity("paskalON.OperatingModes.Domain.Configs.ClosedModes.VoltageReactives.VoltageVarDroopModeConfig", b =>
                {
                    b.HasBaseType("paskalON.OperatingModes.Domain.Configs.OperatingModeBaseConfig");

                    b.Property<double>("DeadbandError")
                        .HasColumnType("double precision");

                    b.ToTable("VoltageVarDroopModeConfig");
                });

            modelBuilder.Entity("paskalON.OperatingModes.Domain.Configs.OpenModes.EnergyResources.MaximumPowerPointTrackingModeConfig", b =>
                {
                    b.HasBaseType("paskalON.OperatingModes.Domain.Configs.OperatingModeBaseConfig");

                    b.ToTable("MaximumPowerPointTrackingModeConfig");
                });

            modelBuilder.Entity("paskalON.OperatingModes.Domain.Configs.OpenModes.FrequencyActives.ActivePowerFixedModeConfig", b =>
                {
                    b.HasBaseType("paskalON.OperatingModes.Domain.Configs.OperatingModeBaseConfig");

                    b.ToTable("ActivePowerFixedModeConfig");
                });

            modelBuilder.Entity("paskalON.OperatingModes.Domain.Configs.OpenModes.MaintenanceModeConfig", b =>
                {
                    b.HasBaseType("paskalON.OperatingModes.Domain.Configs.OperatingModeBaseConfig");

                    b.Property<string>("DerUnitName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ToTable("MaintenanceModeConfig");
                });

            modelBuilder.Entity("paskalON.OperatingModes.Domain.Configs.OpenModes.VoltageReactives.ReactivePowerFixedModeConfig", b =>
                {
                    b.HasBaseType("paskalON.OperatingModes.Domain.Configs.OperatingModeBaseConfig");

                    b.ToTable("ReactivePowerFixedModeConfig");
                });

            modelBuilder.Entity("paskalON.OperatingModes.Domain.Configs.Curves.CurvePointConfig", b =>
                {
                    b.HasOne("paskalON.OperatingModes.Domain.Configs.Curves.CurveBaseConfig", "CurveBaseConfig")
                        .WithMany("Points")
                        .HasForeignKey("CurveBaseConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CurveBaseConfig");
                });

            modelBuilder.Entity("paskalON.OperatingModes.Domain.Configs.OperatingModeBaseConfig", b =>
                {
                    b.HasOne("paskalON.OperatingModes.Domain.Configs.Curves.CurveBaseConfig", "CurveConfig")
                        .WithMany()
                        .HasForeignKey("CurveConfigId");

                    b.HasOne("paskalON.OperatingModes.Domain.Configs.Ramps.RampBaseConfig", "RampConfig")
                        .WithMany()
                        .HasForeignKey("RampConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CurveConfig");

                    b.Navigation("RampConfig");
                });

            modelBuilder.Entity("paskalON.OperatingModes.Domain.Configs.Curves.CurveBaseConfig", b =>
                {
                    b.Navigation("Points");
                });
#pragma warning restore 612, 618
        }
    }
}
