#------------------------------------------------------------------------------
# Variables
#------------------------------------------------------------------------------
@paskalON.OperatingModes.Service_HostAddress = http://localhost:5176

#------------------------------------------------------------------------------
# Version controller
#------------------------------------------------------------------------------
GET {{paskalON.OperatingModes.Service_HostAddress}}/api/v1/version/
Accept: application/json

###