// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using paskalON.Devices.Infrastructure.Storage;

#nullable disable

namespace paskalON.Devices.Infrastructure.Storage.Migrations
{
    [DbContext(typeof(DeviceServiceContext))]
    [Migration("20260828032218_v_0_1")]
    partial class v_0_1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence("DomainBaseSequence");

            modelBuilder.Entity("paskalON.Communication.Protocols.Modbus.Configurations.ModbusRegisterMapEntryConfig", b =>
                {
                    b.Property<int>("ModbusRegisterMapEntryConfigId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ModbusRegisterMapEntryConfigId"));

                    b.Property<int>("Index")
                        .HasColumnType("integer");

                    b.Property<int>("IndividualOffset")
                        .HasColumnType("integer");

                    b.Property<int?>("ModbusRegisterFormat")
                        .HasColumnType("integer");

                    b.Property<double>("Scale")
                        .HasColumnType("double precision");

                    b.Property<int?>("UnitPrefix")
                        .HasColumnType("integer");

                    b.HasKey("ModbusRegisterMapEntryConfigId");

                    b.ToTable("ModbusRegisterMapEntryConfig");
                });

            modelBuilder.Entity("paskalON.Communication.Protocols.Modbus.Configurations.ModbusRegisterMapPollingRangeConfig", b =>
                {
                    b.Property<int>("ModbusRegisterMapPollingRangeConfigId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ModbusRegisterMapPollingRangeConfigId"));

                    b.Property<int>("End")
                        .HasColumnType("integer");

                    b.Property<bool>("IsInputRegisterRange")
                        .HasColumnType("boolean");

                    b.Property<string>("PollingClass")
                        .HasColumnType("text");

                    b.Property<int?>("PowerMeterMapModbusConfigId")
                        .HasColumnType("integer");

                    b.Property<int>("Start")
                        .HasColumnType("integer");

                    b.HasKey("ModbusRegisterMapPollingRangeConfigId");

                    b.HasIndex("PowerMeterMapModbusConfigId");

                    b.ToTable("ModbusRegisterMapPollingRangeConfig");
                });

            modelBuilder.Entity("paskalON.Domains.DomainBase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValueSql("nextval('\"DomainBaseSequence\"')");

                    NpgsqlPropertyBuilderExtensions.UseSequence(b.Property<int>("Id"));

                    b.Property<string>("ChangedBy")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<DateTimeOffset>("ChangedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable((string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("paskalON.Domains.History", b =>
                {
                    b.Property<string>("MigrationId")
                        .HasColumnType("text");

                    b.Property<string>("ProductVersion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MigrationId");

                    b.ToTable("__EFMigrationsHistory", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("paskalON.Domains.ConfigurationBase", b =>
                {
                    b.HasBaseType("paskalON.Domains.DomainBase");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(800)
                        .HasColumnType("character varying(800)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.ToTable((string)null);
                });

            modelBuilder.Entity("paskalON.Domains.NameBase", b =>
                {
                    b.HasBaseType("paskalON.Domains.DomainBase");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable((string)null);
                });

            modelBuilder.Entity("paskalON.Devices.Domain.Configs.Configuration", b =>
                {
                    b.HasBaseType("paskalON.Domains.ConfigurationBase");

                    b.ToTable("Configuration");
                });

            modelBuilder.Entity("paskalON.Devices.Domain.Configs.EnergyStorages.Batteries.BatteryBankDeviceCustomConfig", b =>
                {
                    b.HasBaseType("paskalON.Domains.ConfigurationBase");

                    b.Property<int>("BatteryBankDeviceConfigId")
                        .HasColumnType("integer");

                    b.HasIndex("BatteryBankDeviceConfigId");

                    b.ToTable("BatteryBankDeviceCustomConfig");
                });

            modelBuilder.Entity("paskalON.Devices.Domain.Configs.PowerConversionSystems.PowerConversionSystemDeviceCustomConfig", b =>
                {
                    b.HasBaseType("paskalON.Domains.ConfigurationBase");

                    b.Property<int>("PowerConversionSystemDeviceConfigId")
                        .HasColumnType("integer");

                    b.HasIndex("PowerConversionSystemDeviceConfigId");

                    b.ToTable("PowerConversionSystemDeviceCustomConfig");
                });

            modelBuilder.Entity("paskalON.Devices.Domain.Configs.C37Config", b =>
                {
                    b.HasBaseType("paskalON.Domains.NameBase");

                    b.Property<int>("ConfigFrameTimeoutMilliseconds")
                        .HasColumnType("integer");

                    b.Property<int>("DataFrameRetryCount")
                        .HasColumnType("integer");

                    b.Property<int>("DataFrameTimeoutMilliseconds")
                        .HasColumnType("integer");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Port")
                        .HasColumnType("integer");

                    b.Property<string>("StationName")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<int>("StreamId")
                        .HasColumnType("integer");

                    b.Property<int>("TransportLayer")
                        .HasColumnType("integer");

                    b.ToTable("C37Config");
                });

            modelBuilder.Entity("paskalON.Devices.Domain.Configs.Ders.DerCircuitConfig", b =>
                {
                    b.HasBaseType("paskalON.Domains.NameBase");

                    b.Property<int>("DerGroupConfigId")
                        .HasColumnType("integer");

                    b.HasIndex("DerGroupConfigId");

                    b.ToTable("DerCircuitConfig");
                });

            modelBuilder.Entity("paskalON.Devices.Domain.Configs.Ders.DerConfig", b =>
                {
                    b.HasBaseType("paskalON.Domains.NameBase");

                    b.ToTable("DerConfig");
                });

            modelBuilder.Entity("paskalON.Devices.Domain.Configs.Ders.DerContainerConfig", b =>
                {
                    b.HasBaseType("paskalON.Domains.NameBase");

                    b.Property<int>("DerUnitConfigId")
                        .HasColumnType("integer");

                    b.Property<int>("DeviceId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("MetricsFactorClass1")
                        .HasColumnType("integer");

                    b.Property<int>("MetricsFactorClass2")
                        .HasColumnType("integer");

                    b.Property<int>("MetricsFactorClass3")
                        .HasColumnType("integer");

                    b.Property<int>("MetricsFactorClass4")
                        .HasColumnType("integer");

                    b.Property<long>("MetricsIntervalMilliseconds")
                        .HasColumnType("bigint");

                    b.Property<int?>("ModbusConfigId")
                        .HasColumnType("integer");

                    b.HasIndex("DerUnitConfigId")
                        .IsUnique();

                    b.HasIndex("DeviceId")
                        .IsUnique();

                    b.HasIndex("ModbusConfigId");

                    b.ToTable("DerContainerConfig");
                });

            modelBuilder.Entity("paskalON.Devices.Domain.Configs.Ders.DerGroupConfig", b =>
                {
                    b.HasBaseType("paskalON.Domains.NameBase");

                    b.Property<int>("DerConfigId")
                        .HasColumnType("integer");

                    b.HasIndex("DerConfigId");

                    b.ToTable("DerGroupConfig");
                });

            modelBuilder.Entity("paskalON.Devices.Domain.Configs.Ders.DerUnitConfig", b =>
                {
                    b.HasBaseType("paskalON.Domains.NameBase");

                    b.Property<int>("DerCircuitConfigId")
                        .HasColumnType("integer");

                    b.Property<bool>("InMaintenanceMode")
                        .HasColumnType("boolean");

                    b.HasIndex("DerCircuitConfigId");

                    b.ToTable((string)null);
                });

            modelBuilder.Entity("paskalON.Devices.Domain.Configs.EnergyResources.Solars.SolarPanelConfig", b =>
                {
                    b.HasBaseType("paskalON.Domains.NameBase");

                    b.Property<int>("ConnectionType")
                        .HasColumnType("integer");

                    b.Property<int>("DerUnitConfigId")
                        .HasColumnType("integer");

                    b.Property<int>("DeviceId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("MetricsFactorClass1")
                        .HasColumnType("integer");

                    b.Property<int>("MetricsFactorClass2")
                        .HasColumnType("integer");

                    b.Property<int>("MetricsFactorClass3")
                        .HasColumnType("integer");

                    b.Property<int>("MetricsFactorClass4")
                        .HasColumnType("integer");

                    b.Property<long>("MetricsIntervalMilliseconds")
                        .HasColumnType("bigint");

                    b.Property<int>("NumberOfPanels")
                        .HasColumnType("integer");

                    b.Property<int>("SolarPanelDeviceConfigId")
                        .HasColumnType("integer");

                    b.HasIndex("DerUnitConfigId")
                        .IsUnique();

                    b.HasIndex("DeviceId")
                        .IsUnique();

                    b.HasIndex("SolarPanelDeviceConfigId");

                    b.ToTable("SolarPanelConfig");
                });

            modelBuilder.Entity("paskalON.Devices.Domain.Configs.EnergyResources.Solars.SolarPanelDeviceConfig", b =>
                {
                    b.HasBaseType("paskalON.Domains.NameBase");

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("MaximumCurrent")
                        .HasColumnType("double precision");

                    b.Property<double>("MaximumVoltage")
                        .HasColumnType("double precision");

                    b.Property<double>("MinimumCurrent")
                        .HasColumnType("double precision");

                    b.Property<double>("MinimumVoltage")
                        .HasColumnType("double precision");

                    b.ToTable("SolarPanelDeviceConfig");
                });

            modelBuilder.Entity("paskalON.Devices.Domain.Configs.EnergyStorages.Batteries.BatteryBankConfig", b =>
                {
                    b.HasBaseType("paskalON.Domains.NameBase");

                    b.Property<int>("BatteryBankDeviceConfigId")
                        .HasColumnType("integer");

                    b.Property<int>("DerUnitConfigId")
                        .HasColumnType("integer");

                    b.Property<int>("DeviceId")
                        .HasColumnType("integer");

                    b.Property<bool>("InitiallyConnected")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("MetricsFactorClass1")
                        .HasColumnType("integer");

                    b.Property<int>("MetricsFactorClass2")
                        .HasColumnType("integer");

                    b.Property<int>("MetricsFactorClass3")
                        .HasColumnType("integer");

                    b.Property<int>("MetricsFactorClass4")
                        .HasColumnType("integer");

                    b.Property<long>("MetricsIntervalMilliseconds")
                        .HasColumnType("bigint");

                    b.Property<int>("ModbusConfigId")
                        .HasColumnType("integer");

                    b.HasIndex("BatteryBankDeviceConfigId");

                    b.HasIndex("DerUnitConfigId");

                    b.HasIndex("DeviceId")
                        .IsUnique();

                    b.HasIndex("ModbusConfigId");

                    b.ToTable("BatteryBankConfig");
                });

            modelBuilder.Entity("paskalON.Devices.Domain.Configs.EnergyStorages.Batteries.BatteryBankDeviceConfig", b =>
                {
                    b.HasBaseType("paskalON.Domains.NameBase");

                    b.Property<double>("AbsoluteMaxChargeCurrentAmps")
                        .HasColumnType("double precision");

                    b.Property<double>("AbsoluteMaxDischargeCurrentAmps")
                        .HasColumnType("double precision");

                    b.Property<double>("AbsoluteMaximumStateOfCharge")
                        .HasColumnType("double precision");

                    b.Property<double>("AbsoluteMaximumTemperature")
                        .HasColumnType("double precision");

                    b.Property<double>("AbsoluteMinimumStateOfCharge")
                        .HasColumnType("double precision");

                    b.Property<double>("AbsoluteMinimumTemperature")
                        .HasColumnType("double precision");

                    b.Property<int>("BatteryType")
                        .HasColumnType("integer");

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("InverterBusNumber")
                        .HasColumnType("integer");

                    b.Property<double>("MaximumDcVoltage")
                        .HasColumnType("double precision");

                    b.Property<double>("MinimumDcVoltage")
                        .HasColumnType("double precision");

                    b.Property<int>("ModulesPerRackCount")
                        .HasColumnType("integer");

                    b.Property<double>("NameplateCapacity")
                        .HasColumnType("double precision");

                    b.Property<double>("NameplateMaximumChargeRate")
                        .HasColumnType("double precision");

                    b.Property<double>("NameplateMaximumDischargeRate")
                        .HasColumnType("double precision");

                    b.Property<double>("PreferredMaximumStateOfCharge")
                        .HasColumnType("double precision");

                    b.Property<double>("PreferredMaximumTemperature")
                        .HasColumnType("double precision");

                    b.Property<double>("PreferredMinimumStateOfCharge")
                        .HasColumnType("double precision");

                    b.Property<double>("PreferredMinimumTemperature")
                        .HasColumnType("double precision");

                    b.Property<int>("RackCount")
                        .HasColumnType("integer");

                    b.Property<bool>("ZeroCapacityOnCommLoss")
                        .HasColumnType("boolean");

                    b.ToTable("BatteryBankDeviceConfig");
                });

            modelBuilder.Entity("paskalON.Devices.Domain.Configs.GenericModbusDevices.AutomaticTransferSwitchDeviceConfig", b =>
                {
                    b.HasBaseType("paskalON.Domains.NameBase");

                    b.Property<int?>("BackupConnectedId")
                        .HasColumnType("integer");

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("GenericModbusMapConfigId")
                        .HasColumnType("integer");

                    b.Property<int?>("GridConnectedId")
                        .HasColumnType("integer");

                    b.HasIndex("BackupConnectedId");

                    b.HasIndex("GenericModbusMapConfigId");

                    b.HasIndex("GridConnectedId");

                    b.ToTable("AutomaticTransferSwitchDeviceConfig");
                });

            modelBuilder.Entity("paskalON.Devices.Domain.Configs.GenericModbusDevices.CircuitBreakerDeviceConfig", b =>
                {
                    b.HasBaseType("paskalON.Domains.NameBase");

                    b.Property<int?>("BreakerStateRegisterId")
                        .HasColumnType("integer");

                    b.Property<int>("CircuitBreakerOperation")
                        .HasColumnType("integer");

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("CloseCommandCoilId")
                        .HasColumnType("integer");

                    b.Property<int?>("CloseCommandId")
                        .HasColumnType("integer");

                    b.Property<int?>("GenericModbusMapConfigId")
                        .HasColumnType("integer");

                    b.Property<int>("OpenBreakerDelayMilliseconds")
                        .HasColumnType("integer");

                    b.Property<int?>("OpenCommandCoilId")
                        .HasColumnType("integer");

                    b.Property<int?>("OpenCommandId")
                        .HasColumnType("integer");

                    b.Property<int?>("ResetTripId")
                        .HasColumnType("integer");

                    b.Property<int?>("SettingsGroupCommandId")
                        .HasColumnType("integer");

                    b.Property<int?>("SettingsGroupStateId")
                        .HasColumnType("integer");

                    b.Property<int?>("SynchronousVoltageId")
                        .HasColumnType("integer");

                    b.Property<int?>("TripStateId")
                        .HasColumnType("integer");

                    b.HasIndex("BreakerStateRegisterId");

                    b.HasIndex("CloseCommandCoilId");

                    b.HasIndex("CloseCommandId");

                    b.HasIndex("GenericModbusMapConfigId");

                    b.HasIndex("OpenCommandCoilId");

                    b.HasIndex("OpenCommandId");

                    b.HasIndex("ResetTripId");

                    b.HasIndex("SettingsGroupCommandId");

                    b.HasIndex("SettingsGroupStateId");

                    b.HasIndex("SynchronousVoltageId");

                    b.HasIndex("TripStateId");

                    b.ToTable("CircuitBreakerDeviceConfig");
                });

            modelBuilder.Entity("paskalON.Devices.Domain.Configs.GenericModbusDevices.GenericModbusDeviceConfig", b =>
                {
                    b.HasBaseType("paskalON.Domains.NameBase");

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("GenericModbusMapConfigId")
                        .HasColumnType("integer");

                    b.HasIndex("GenericModbusMapConfigId");

                    b.ToTable("GenericModbusDeviceConfig");
                });

            modelBuilder.Entity("paskalON.Devices.Domain.Configs.GenericModbusDevices.Maps.GenericModbusCoilPointConfig", b =>
                {
                    b.HasBaseType("paskalON.Domains.NameBase");

                    b.Property<int>("GenericModbusMapConfigId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsAlarm")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsAlarmReset")
                        .HasColumnType("boolean");

                    b.Property<int>("ModbusDataType")
                        .HasColumnType("integer");

                    b.Property<int>("ModbusNumber")
                        .HasColumnType("integer");

                    b.Property<int>("PollingInterval")
                        .HasColumnType("integer");

                    b.HasIndex("GenericModbusMapConfigId");

                    b.ToTable("GenericModbusCoilPointConfig");
                });

            modelBuilder.Entity("paskalON.Devices.Domain.Configs.GenericModbusDevices.Maps.GenericModbusDiscreteInputPointConfig", b =>
                {
                    b.HasBaseType("paskalON.Domains.NameBase");

                    b.Property<int>("GenericModbusMapConfigId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsAlarm")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsAlarmReset")
                        .HasColumnType("boolean");

                    b.Property<int>("ModbusDataType")
                        .HasColumnType("integer");

                    b.Property<int>("ModbusNumber")
                        .HasColumnType("integer");

                    b.Property<int>("PollingInterval")
                        .HasColumnType("integer");

                    b.HasIndex("GenericModbusMapConfigId");

                    b.ToTable("GenericModbusDiscreteInputPointConfig");
                });

            modelBuilder.Entity("paskalON.Devices.Domain.Configs.GenericModbusDevices.Maps.GenericModbusHoldingRegisterConfig", b =>
                {
                    b.HasBaseType("paskalON.Domains.NameBase");

                    b.Property<short>("BitIndex")
                        .HasColumnType("smallint");

                    b.Property<int>("GenericModbusMapConfigId")
                        .HasColumnType("integer");

                    b.Property<int>("IndividualOffset")
                        .HasColumnType("integer");

                    b.Property<int>("ModbusDataType")
                        .HasColumnType("integer");

                    b.Property<int>("ModbusNumber")
                        .HasColumnType("integer");

                    b.Property<double>("ModbusScale")
                        .HasColumnType("double precision");

                    b.Property<int>("PollingInterval")
                        .HasColumnType("integer");

                    b.Property<bool>("ReverseSign")
                        .HasColumnType("boolean");

                    b.HasIndex("GenericModbusMapConfigId");

                    b.ToTable("GenericModbusHoldingRegisterConfig");
                });

            modelBuilder.Entity("paskalON.Devices.Domain.Configs.GenericModbusDevices.Maps.GenericModbusInputRegisterConfig", b =>
                {
                    b.HasBaseType("paskalON.Domains.NameBase");

                    b.Property<short>("BitIndex")
                        .HasColumnType("smallint");

                    b.Property<int>("GenericModbusMapConfigId")
                        .HasColumnType("integer");

                    b.Property<int>("IndividualOffset")
                        .HasColumnType("integer");

                    b.Property<int>("ModbusDataType")
                        .HasColumnType("integer");

                    b.Property<int>("ModbusNumber")
                        .HasColumnType("integer");

                    b.Property<double>("ModbusScale")
                        .HasColumnType("double precision");

                    b.Property<int>("PollingInterval")
                        .HasColumnType("integer");

                    b.Property<bool>("ReverseSign")
                        .HasColumnType("boolean");

                    b.HasIndex("GenericModbusMapConfigId");

                    b.ToTable("GenericModbusInputRegisterConfig");
                });

            modelBuilder.Entity("paskalON.Devices.Domain.Configs.GenericModbusDevices.Maps.GenericModbusMapConfig", b =>
                {
                    b.HasBaseType("paskalON.Domains.NameBase");

                    b.Property<int>("MasterHeartbeatPollingInterval")
                        .HasColumnType("integer");

                    b.Property<int?>("MasterHeartbeatRegister")
                        .HasColumnType("integer");

                    b.Property<int?>("SlaveHeartbeatRegister")
                        .HasColumnType("integer");

                    b.ToTable("GenericModbusMapConfig");
                });

            modelBuilder.Entity("paskalON.Devices.Domain.Configs.Meters.PowerMeters.PowerMeterBaseConfig", b =>
                {
                    b.HasBaseType("paskalON.Domains.NameBase");

                    b.Property<int?>("C37ConfigId")
                        .HasColumnType("integer");

                    b.Property<int>("DeviceId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("MetricsFactorClass1")
                        .HasColumnType("integer");

                    b.Property<int>("MetricsFactorClass2")
                        .HasColumnType("integer");

                    b.Property<int>("MetricsFactorClass3")
                        .HasColumnType("integer");

                    b.Property<int>("MetricsFactorClass4")
                        .HasColumnType("integer");

                    b.Property<long>("MetricsIntervalMilliseconds")
                        .HasColumnType("bigint");

                    b.Property<int?>("ModbusConfigId")
                        .HasColumnType("integer");

                    b.Property<int>("PowerFactorStandard")
                        .HasColumnType("integer");

                    b.Property<int>("PowerMeterDeviceConfigId")
                        .HasColumnType("integer");

                    b.Property<int?>("RedundantPowerMeterConfigId")
                        .HasColumnType("integer");

                    b.HasIndex("C37ConfigId");

                    b.HasIndex("DeviceId")
                        .IsUnique();

                    b.HasIndex("ModbusConfigId");

                    b.HasIndex("PowerMeterDeviceConfigId");

                    b.HasIndex("RedundantPowerMeterConfigId");

                    b.ToTable((string)null);
                });

            modelBuilder.Entity("paskalON.Devices.Domain.Configs.Meters.PowerMeters.PowerMeterDeviceConfig", b =>
                {
                    b.HasBaseType("paskalON.Domains.NameBase");

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsCurrentSigned")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsReversePowerFlow")
                        .HasColumnType("boolean");

                    b.Property<int?>("PowerMeterMapC37ConfigId")
                        .HasColumnType("integer");

                    b.Property<int?>("PowerMeterMapModbusConfigId")
                        .HasColumnType("integer");

                    b.HasIndex("PowerMeterMapC37ConfigId");

                    b.HasIndex("PowerMeterMapModbusConfigId");

                    b.ToTable("PowerMeterDeviceConfig");
                });

            modelBuilder.Entity("paskalON.Devices.Domain.Configs.Meters.PowerMeters.PowerMeterMapC37Config", b =>
                {
                    b.HasBaseType("paskalON.Domains.NameBase");

                    b.Property<string>("ActivePower")
                        .HasColumnType("text");

                    b.Property<string>("ActivePowerA")
                        .HasColumnType("text");

                    b.Property<string>("ActivePowerB")
                        .HasColumnType("text");

                    b.Property<string>("ActivePowerC")
                        .HasColumnType("text");

                    b.Property<string>("ApparentPower")
                        .HasColumnType("text");

                    b.Property<string>("CurrentA")
                        .HasColumnType("text");

                    b.Property<string>("CurrentB")
                        .HasColumnType("text");

                    b.Property<string>("CurrentC")
                        .HasColumnType("text");

                    b.Property<string>("EnergyDelivered")
                        .HasColumnType("text");

                    b.Property<string>("EnergyReceived")
                        .HasColumnType("text");

                    b.Property<string>("ReactiveEnergyDelivered")
                        .HasColumnType("text");

                    b.Property<string>("ReactiveEnergyReceived")
                        .HasColumnType("text");

                    b.Property<string>("ReactivePower")
                        .HasColumnType("text");

                    b.Property<string>("ReactivePowerA")
                        .HasColumnType("text");

                    b.Property<string>("ReactivePowerB")
                        .HasColumnType("text");

                    b.Property<string>("ReactivePowerC")
                        .HasColumnType("text");

                    b.Property<string>("VoltageA")
                        .HasColumnType("text");

                    b.Property<string>("VoltageAB")
                        .HasColumnType("text");

                    b.Property<string>("VoltageB")
                        .HasColumnType("text");

                    b.Property<string>("VoltageBC")
                        .HasColumnType("text");

                    b.Property<string>("VoltageC")
                        .HasColumnType("text");

                    b.Property<string>("VoltageCA")
                        .HasColumnType("text");

                    b.Property<string>("VoltageLLAvg")
                        .HasColumnType("text");

                    b.Property<string>("VoltagePositiveSequence")
                        .HasColumnType("text");

                    b.ToTable("PowerMeterMapC37Config");
                });

            modelBuilder.Entity("paskalON.Devices.Domain.Configs.Meters.PowerMeters.PowerMeterMapModbusConfig", b =>
                {
                    b.HasBaseType("paskalON.Domains.NameBase");

                    b.Property<int?>("ActivePowerAMapModbusRegisterMapEntryConfigId")
                        .HasColumnType("integer");

                    b.Property<int?>("ActivePowerBMapModbusRegisterMapEntryConfigId")
                        .HasColumnType("integer");

                    b.Property<int?>("ActivePowerCMapModbusRegisterMapEntryConfigId")
                        .HasColumnType("integer");

                    b.Property<int?>("ActivePowerMapModbusRegisterMapEntryConfigId")
                        .HasColumnType("integer");

                    b.Property<int?>("ApparentPowerMapModbusRegisterMapEntryConfigId")
                        .HasColumnType("integer");

                    b.Property<int?>("CurrentAMapModbusRegisterMapEntryConfigId")
                        .HasColumnType("integer");

                    b.Property<int?>("CurrentBMapModbusRegisterMapEntryConfigId")
                        .HasColumnType("integer");

                    b.Property<int?>("CurrentCMapModbusRegisterMapEntryConfigId")
                        .HasColumnType("integer");

                    b.Property<int?>("EnergyDeliveredMapModbusRegisterMapEntryConfigId")
                        .HasColumnType("integer");

                    b.Property<int?>("EnergyReceivedMapModbusRegisterMapEntryConfigId")
                        .HasColumnType("integer");

                    b.Property<int?>("FrequencyMapModbusRegisterMapEntryConfigId")
                        .HasColumnType("integer");

                    b.Property<int?>("PowerFactorMapModbusRegisterMapEntryConfigId")
                        .HasColumnType("integer");

                    b.Property<int?>("ReactiveEnergyDeliveredMapModbusRegisterMapEntryConfigId")
                        .HasColumnType("integer");

                    b.Property<int?>("ReactiveEnergyReceivedMapModbusRegisterMapEntryConfigId")
                        .HasColumnType("integer");

                    b.Property<int?>("ReactivePowerAMapModbusRegisterMapEntryConfigId")
                        .HasColumnType("integer");

                    b.Property<int?>("ReactivePowerBMapModbusRegisterMapEntryConfigId")
                        .HasColumnType("integer");

                    b.Property<int?>("ReactivePowerCMapModbusRegisterMapEntryConfigId")
                        .HasColumnType("integer");

                    b.Property<int?>("ReactivePowerMapModbusRegisterMapEntryConfigId")
                        .HasColumnType("integer");

                    b.Property<int>("StartingCoil")
                        .HasColumnType("integer");

                    b.Property<int>("StartingDiscreteInput")
                        .HasColumnType("integer");

                    b.Property<int>("StartingHoldingRegister")
                        .HasColumnType("integer");

                    b.Property<int>("StartingInputRegister")
                        .HasColumnType("integer");

                    b.Property<int?>("VoltageAMapModbusRegisterMapEntryConfigId")
                        .HasColumnType("integer");

                    b.Property<int?>("VoltageBMapModbusRegisterMapEntryConfigId")
                        .HasColumnType("integer");

                    b.Property<int?>("VoltageCMapModbusRegisterMapEntryConfigId")
                        .HasColumnType("integer");

                    b.Property<int?>("VoltageLLAvgMapModbusRegisterMapEntryConfigId")
                        .HasColumnType("integer");

                    b.HasIndex("ActivePowerAMapModbusRegisterMapEntryConfigId");

                    b.HasIndex("ActivePowerBMapModbusRegisterMapEntryConfigId");

                    b.HasIndex("ActivePowerCMapModbusRegisterMapEntryConfigId");

                    b.HasIndex("ActivePowerMapModbusRegisterMapEntryConfigId");

                    b.HasIndex("ApparentPowerMapModbusRegisterMapEntryConfigId");

                    b.HasIndex("CurrentAMapModbusRegisterMapEntryConfigId");

                    b.HasIndex("CurrentBMapModbusRegisterMapEntryConfigId");

                    b.HasIndex("CurrentCMapModbusRegisterMapEntryConfigId");

                    b.HasIndex("EnergyDeliveredMapModbusRegisterMapEntryConfigId");

                    b.HasIndex("EnergyReceivedMapModbusRegisterMapEntryConfigId");

                    b.HasIndex("FrequencyMapModbusRegisterMapEntryConfigId");

                    b.HasIndex("PowerFactorMapModbusRegisterMapEntryConfigId");

                    b.HasIndex("ReactiveEnergyDeliveredMapModbusRegisterMapEntryConfigId");

                    b.HasIndex("ReactiveEnergyReceivedMapModbusRegisterMapEntryConfigId");

                    b.HasIndex("ReactivePowerAMapModbusRegisterMapEntryConfigId");

                    b.HasIndex("ReactivePowerBMapModbusRegisterMapEntryConfigId");

                    b.HasIndex("ReactivePowerCMapModbusRegisterMapEntryConfigId");

                    b.HasIndex("ReactivePowerMapModbusRegisterMapEntryConfigId");

                    b.HasIndex("VoltageAMapModbusRegisterMapEntryConfigId");

                    b.HasIndex("VoltageBMapModbusRegisterMapEntryConfigId");

                    b.HasIndex("VoltageCMapModbusRegisterMapEntryConfigId");

                    b.HasIndex("VoltageLLAvgMapModbusRegisterMapEntryConfigId");

                    b.ToTable("PowerMeterMapModbusConfig");
                });

            modelBuilder.Entity("paskalON.Devices.Domain.Configs.ModbusConfig", b =>
                {
                    b.HasBaseType("paskalON.Domains.NameBase");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("AddressFamily")
                        .HasColumnType("integer");

                    b.Property<int>("ModbusConnectionConfigId")
                        .HasColumnType("integer");

                    b.Property<int>("Port")
                        .HasColumnType("integer");

                    b.Property<byte>("StationId")
                        .HasColumnType("smallint");

                    b.HasIndex("ModbusConnectionConfigId");

                    b.ToTable("ModbusConfig");
                });

            modelBuilder.Entity("paskalON.Devices.Domain.Configs.ModbusConnectionConfig", b =>
                {
                    b.HasBaseType("paskalON.Domains.NameBase");

                    b.Property<int>("ConnectRetryCount")
                        .HasColumnType("integer");

                    b.Property<int>("ConnectRetryIntervalMilliseconds")
                        .HasColumnType("integer");

                    b.Property<int>("ConnectionTimeoutMilliseconds")
                        .HasColumnType("integer");

                    b.Property<int>("DisconnectionTimeoutMilliseconds")
                        .HasColumnType("integer");

                    b.Property<bool>("IsPipeliningEnabled")
                        .HasColumnType("boolean");

                    b.Property<long>("MasterHeartBeatIntervalMilliseconds")
                        .HasColumnType("bigint");

                    b.Property<int>("PollingFactorClass1")
                        .HasColumnType("integer");

                    b.Property<int>("PollingFactorClass2")
                        .HasColumnType("integer");

                    b.Property<int>("PollingFactorClass3")
                        .HasColumnType("integer");

                    b.Property<int>("PollingFactorClass4")
                        .HasColumnType("integer");

                    b.Property<int>("PollingFactorClass5")
                        .HasColumnType("integer");

                    b.Property<long>("PollingIntervalMilliseconds")
                        .HasColumnType("bigint");

                    b.Property<int>("SendRetryCount")
                        .HasColumnType("integer");

                    b.Property<int>("SendRetryIntervalMilliseconds")
                        .HasColumnType("integer");

                    b.Property<int>("SendTimeoutMilliseconds")
                        .HasColumnType("integer");

                    b.Property<int>("ServerMaximumConnections")
                        .HasColumnType("integer");

                    b.Property<int>("ServerToClientAliveIntervalSeconds")
                        .HasColumnType("integer");

                    b.ToTable("ModbusConnectionConfig");
                });

            modelBuilder.Entity("paskalON.Devices.Domain.Configs.PowerConversionSystems.PowerConversionSystemConfig", b =>
                {
                    b.HasBaseType("paskalON.Domains.NameBase");

                    b.Property<int>("DerUnitConfigId")
                        .HasColumnType("integer");

                    b.Property<int>("DeviceId")
                        .HasColumnType("integer");

                    b.Property<bool>("InitiallyStarted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("MetricsFactorClass1")
                        .HasColumnType("integer");

                    b.Property<int>("MetricsFactorClass2")
                        .HasColumnType("integer");

                    b.Property<int>("MetricsFactorClass3")
                        .HasColumnType("integer");

                    b.Property<int>("MetricsFactorClass4")
                        .HasColumnType("integer");

                    b.Property<long>("MetricsIntervalMilliseconds")
                        .HasColumnType("bigint");

                    b.Property<int>("ModbusConfigId")
                        .HasColumnType("integer");

                    b.Property<int>("PowerConversionSystemDeviceConfigId")
                        .HasColumnType("integer");

                    b.HasIndex("DerUnitConfigId")
                        .IsUnique();

                    b.HasIndex("DeviceId")
                        .IsUnique();

                    b.HasIndex("ModbusConfigId");

                    b.HasIndex("PowerConversionSystemDeviceConfigId");

                    b.ToTable("PowerConversionSystemConfig");
                });

            modelBuilder.Entity("paskalON.Devices.Domain.Configs.PowerConversionSystems.PowerConversionSystemDeviceConfig", b =>
                {
                    b.HasBaseType("paskalON.Domains.NameBase");

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("MaximumDCVoltage")
                        .HasColumnType("double precision");

                    b.Property<double>("MinimumDCVoltage")
                        .HasColumnType("double precision");

                    b.Property<double>("NameplateMaximumACCurrent")
                        .HasColumnType("double precision");

                    b.Property<double>("NameplateMaximumActivePower")
                        .HasColumnType("double precision");

                    b.Property<double>("NameplateMaximumApparentPower")
                        .HasColumnType("double precision");

                    b.Property<double>("NameplateMaximumReactivePower")
                        .HasColumnType("double precision");

                    b.Property<double>("StandbyActivePowerKiloWatts")
                        .HasColumnType("double precision");

                    b.Property<bool>("ZeroOutputOnCommLoss")
                        .HasColumnType("boolean");

                    b.ToTable("PowerConversionSystemDeviceConfig");
                });

            modelBuilder.Entity("paskalON.Devices.Domain.Configs.Ders.DerBatteryStorageUnitConfig", b =>
                {
                    b.HasBaseType("paskalON.Devices.Domain.Configs.Ders.DerUnitConfig");

                    b.Property<bool>("IncludeBatteryInOperations")
                        .HasColumnType("boolean");

                    b.ToTable("DerBatteryStorageUnitConfig");
                });

            modelBuilder.Entity("paskalON.Devices.Domain.Configs.Ders.DerSolarUnitConfig", b =>
                {
                    b.HasBaseType("paskalON.Devices.Domain.Configs.Ders.DerUnitConfig");

                    b.Property<int>("SolarPanelConfigId")
                        .HasColumnType("integer");

                    b.ToTable("DerSolarUnitConfig");
                });

            modelBuilder.Entity("paskalON.Devices.Domain.Configs.Meters.PowerMeters.AuxiliaryPowerMeterConfig", b =>
                {
                    b.HasBaseType("paskalON.Devices.Domain.Configs.Meters.PowerMeters.PowerMeterBaseConfig");

                    b.Property<int>("DerConfigId")
                        .HasColumnType("integer");

                    b.HasIndex("DerConfigId");

                    b.ToTable("AuxiliaryPowerMeterConfig");
                });

            modelBuilder.Entity("paskalON.Devices.Domain.Configs.Meters.PowerMeters.CircuitPowerMeterConfig", b =>
                {
                    b.HasBaseType("paskalON.Devices.Domain.Configs.Meters.PowerMeters.PowerMeterBaseConfig");

                    b.Property<int>("DerCircuitConfigId")
                        .HasColumnType("integer");

                    b.HasIndex("DerCircuitConfigId")
                        .IsUnique();

                    b.ToTable("CircuitPowerMeterConfig");
                });

            modelBuilder.Entity("paskalON.Devices.Domain.Configs.Meters.PowerMeters.ExternalPowerMeterConfig", b =>
                {
                    b.HasBaseType("paskalON.Devices.Domain.Configs.Meters.PowerMeters.PowerMeterBaseConfig");

                    b.Property<int>("DerConfigId")
                        .HasColumnType("integer");

                    b.HasIndex("DerConfigId");

                    b.ToTable("ExternalPowerMeterConfig");
                });

            modelBuilder.Entity("paskalON.Devices.Domain.Configs.Meters.PowerMeters.SystemPowerMeterConfig", b =>
                {
                    b.HasBaseType("paskalON.Devices.Domain.Configs.Meters.PowerMeters.PowerMeterBaseConfig");

                    b.Property<int>("DerConfigId")
                        .HasColumnType("integer");

                    b.HasIndex("DerConfigId");

                    b.ToTable("SystemPowerMeterConfig");
                });

            modelBuilder.Entity("paskalON.Devices.Domain.Configs.GenericModbusDevices.AutomaticTransferSwitchConfig", b =>
                {
                    b.HasBaseType("paskalON.Devices.Domain.Configs.ModbusConfig");

                    b.Property<int>("AutomaticTransferSwitchDeviceConfigId")
                        .HasColumnType("integer");

                    b.Property<int>("DerConfigId")
                        .HasColumnType("integer");

                    b.Property<int>("DeviceId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("MetricsFactorClass1")
                        .HasColumnType("integer");

                    b.Property<int>("MetricsFactorClass2")
                        .HasColumnType("integer");

                    b.Property<long>("MetricsIntervalMilliseconds")
                        .HasColumnType("bigint");

                    b.HasIndex("AutomaticTransferSwitchDeviceConfigId");

                    b.HasIndex("DerConfigId");

                    b.HasIndex("DeviceId")
                        .IsUnique();

                    b.ToTable("AutomaticTransferSwitchConfig");
                });

            modelBuilder.Entity("paskalON.Devices.Domain.Configs.GenericModbusDevices.CircuitBreakerConfig", b =>
                {
                    b.HasBaseType("paskalON.Devices.Domain.Configs.ModbusConfig");

                    b.Property<int>("CircuitBreakerDeviceConfigId")
                        .HasColumnType("integer");

                    b.Property<int>("DerCircuitConfigId")
                        .HasColumnType("integer");

                    b.Property<int>("DeviceId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("MetricsFactorClass1")
                        .HasColumnType("integer");

                    b.Property<int>("MetricsFactorClass2")
                        .HasColumnType("integer");

                    b.Property<long>("MetricsIntervalMilliseconds")
                        .HasColumnType("bigint");

                    b.HasIndex("CircuitBreakerDeviceConfigId");

                    b.HasIndex("DerCircuitConfigId")
                        .IsUnique();

                    b.HasIndex("DeviceId")
                        .IsUnique();

                    b.ToTable("CircuitBreakerConfig");
                });

            modelBuilder.Entity("paskalON.Devices.Domain.Configs.GenericModbusDevices.GenericModbusConfig", b =>
                {
                    b.HasBaseType("paskalON.Devices.Domain.Configs.ModbusConfig");

                    b.Property<int>("DerConfigId")
                        .HasColumnType("integer");

                    b.Property<int>("DeviceId")
                        .HasColumnType("integer");

                    b.Property<int>("GenericModbusDeviceConfigId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("MetricsFactorClass1")
                        .HasColumnType("integer");

                    b.Property<int>("MetricsFactorClass2")
                        .HasColumnType("integer");

                    b.Property<long>("MetricsIntervalMilliseconds")
                        .HasColumnType("bigint");

                    b.HasIndex("DerConfigId");

                    b.HasIndex("DeviceId")
                        .IsUnique();

                    b.HasIndex("GenericModbusDeviceConfigId");

                    b.ToTable("GenericModbusConfig");
                });

            modelBuilder.Entity("paskalON.Devices.Domain.Configs.GenericModbusDevices.GenericModbusUnitConfig", b =>
                {
                    b.HasBaseType("paskalON.Devices.Domain.Configs.ModbusConfig");

                    b.Property<int>("DerUnitConfigId")
                        .HasColumnType("integer");

                    b.Property<int>("DeviceId")
                        .HasColumnType("integer");

                    b.Property<int>("GenericModbusDeviceConfigId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("MetricsFactorClass1")
                        .HasColumnType("integer");

                    b.Property<int>("MetricsFactorClass2")
                        .HasColumnType("integer");

                    b.Property<long>("MetricsIntervalMilliseconds")
                        .HasColumnType("bigint");

                    b.HasIndex("DerUnitConfigId")
                        .IsUnique();

                    b.HasIndex("DeviceId")
                        .IsUnique();

                    b.HasIndex("GenericModbusDeviceConfigId");

                    b.ToTable("GenericModbusUnitConfig");
                });

            modelBuilder.Entity("paskalON.Communication.Protocols.Modbus.Configurations.ModbusRegisterMapPollingRangeConfig", b =>
                {
                    b.HasOne("paskalON.Devices.Domain.Configs.Meters.PowerMeters.PowerMeterMapModbusConfig", null)
                        .WithMany("PollingRange")
                        .HasForeignKey("PowerMeterMapModbusConfigId");
                });

            modelBuilder.Entity("paskalON.Devices.Domain.Configs.EnergyStorages.Batteries.BatteryBankDeviceCustomConfig", b =>
                {
                    b.HasOne("paskalON.Devices.Domain.Configs.EnergyStorages.Batteries.BatteryBankDeviceConfig", "BatteryBankDeviceConfig")
                        .WithMany("Customs")
                        .HasForeignKey("BatteryBankDeviceConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BatteryBankDeviceConfig");
                });

            modelBuilder.Entity("paskalON.Devices.Domain.Configs.PowerConversionSystems.PowerConversionSystemDeviceCustomConfig", b =>
                {
                    b.HasOne("paskalON.Devices.Domain.Configs.PowerConversionSystems.PowerConversionSystemDeviceConfig", "PowerConversionSystemDeviceConfig")
                        .WithMany("Customs")
                        .HasForeignKey("PowerConversionSystemDeviceConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PowerConversionSystemDeviceConfig");
                });

            modelBuilder.Entity("paskalON.Devices.Domain.Configs.Ders.DerCircuitConfig", b =>
                {
                    b.HasOne("paskalON.Devices.Domain.Configs.Ders.DerGroupConfig", "DerGroupConfig")
                        .WithMany("DerCircuits")
                        .HasForeignKey("DerGroupConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DerGroupConfig");
                });

            modelBuilder.Entity("paskalON.Devices.Domain.Configs.Ders.DerContainerConfig", b =>
                {
                    b.HasOne("paskalON.Devices.Domain.Configs.Ders.DerUnitConfig", "DerUnitConfig")
                        .WithOne("DerContainerConfig")
                        .HasForeignKey("paskalON.Devices.Domain.Configs.Ders.DerContainerConfig", "DerUnitConfigId");

                    b.HasOne("paskalON.Devices.Domain.Configs.ModbusConfig", "ModbusConfig")
                        .WithMany()
                        .HasForeignKey("ModbusConfigId");

                    b.Navigation("DerUnitConfig");

                    b.Navigation("ModbusConfig");
                });

            modelBuilder.Entity("paskalON.Devices.Domain.Configs.Ders.DerGroupConfig", b =>
                {
                    b.HasOne("paskalON.Devices.Domain.Configs.Ders.DerConfig", "DerConfig")
                        .WithMany("DerGroupConfigs")
                        .HasForeignKey("DerConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DerConfig");
                });

            modelBuilder.Entity("paskalON.Devices.Domain.Configs.Ders.DerUnitConfig", b =>
                {
                    b.HasOne("paskalON.Devices.Domain.Configs.Ders.DerCircuitConfig", "DerCircuitConfig")
                        .WithMany("DerUnitConfigs")
                        .HasForeignKey("DerCircuitConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DerCircuitConfig");
                });

            modelBuilder.Entity("paskalON.Devices.Domain.Configs.EnergyResources.Solars.SolarPanelConfig", b =>
                {
                    b.HasOne("paskalON.Devices.Domain.Configs.Ders.DerSolarUnitConfig", "DerUnitConfig")
                        .WithOne("SolarPanelConfig")
                        .HasForeignKey("paskalON.Devices.Domain.Configs.EnergyResources.Solars.SolarPanelConfig", "DerUnitConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("paskalON.Devices.Domain.Configs.EnergyResources.Solars.SolarPanelDeviceConfig", "SolarPanelDeviceConfig")
                        .WithMany()
                        .HasForeignKey("SolarPanelDeviceConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DerUnitConfig");

                    b.Navigation("SolarPanelDeviceConfig");
                });

            modelBuilder.Entity("paskalON.Devices.Domain.Configs.EnergyStorages.Batteries.BatteryBankConfig", b =>
                {
                    b.HasOne("paskalON.Devices.Domain.Configs.EnergyStorages.Batteries.BatteryBankDeviceConfig", "BatteryBankDeviceConfig")
                        .WithMany()
                        .HasForeignKey("BatteryBankDeviceConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("paskalON.Devices.Domain.Configs.Ders.DerBatteryStorageUnitConfig", "DerUnitConfig")
                        .WithMany("BatteryBankConfigs")
                        .HasForeignKey("DerUnitConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("paskalON.Devices.Domain.Configs.ModbusConfig", "ModbusConfig")
                        .WithMany()
                        .HasForeignKey("ModbusConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BatteryBankDeviceConfig");

                    b.Navigation("DerUnitConfig");

                    b.Navigation("ModbusConfig");
                });

            modelBuilder.Entity("paskalON.Devices.Domain.Configs.GenericModbusDevices.AutomaticTransferSwitchDeviceConfig", b =>
                {
                    b.HasOne("paskalON.Devices.Domain.Configs.GenericModbusDevices.Maps.GenericModbusCoilPointConfig", "BackupConnected")
                        .WithMany()
                        .HasForeignKey("BackupConnectedId");

                    b.HasOne("paskalON.Devices.Domain.Configs.GenericModbusDevices.Maps.GenericModbusMapConfig", "GenericModbusMapConfig")
                        .WithMany()
                        .HasForeignKey("GenericModbusMapConfigId");

                    b.HasOne("paskalON.Devices.Domain.Configs.GenericModbusDevices.Maps.GenericModbusCoilPointConfig", "GridConnected")
                        .WithMany()
                        .HasForeignKey("GridConnectedId")
                        .HasConstraintName("FK_AutomaticTransferSwitchDeviceConfig_GenericModbusCoilPoint~1");

                    b.Navigation("BackupConnected");

                    b.Navigation("GenericModbusMapConfig");

                    b.Navigation("GridConnected");
                });

            modelBuilder.Entity("paskalON.Devices.Domain.Configs.GenericModbusDevices.CircuitBreakerDeviceConfig", b =>
                {
                    b.HasOne("paskalON.Devices.Domain.Configs.GenericModbusDevices.Maps.GenericModbusHoldingRegisterConfig", "BreakerStateRegister")
                        .WithMany()
                        .HasForeignKey("BreakerStateRegisterId");

                    b.HasOne("paskalON.Devices.Domain.Configs.GenericModbusDevices.Maps.GenericModbusCoilPointConfig", "CloseCommandCoil")
                        .WithMany()
                        .HasForeignKey("CloseCommandCoilId");

                    b.HasOne("paskalON.Devices.Domain.Configs.GenericModbusDevices.Maps.GenericModbusHoldingRegisterConfig", "CloseCommand")
                        .WithMany()
                        .HasForeignKey("CloseCommandId")
                        .HasConstraintName("FK_CircuitBreakerDeviceConfig_GenericModbusHoldingRegisterCon~1");

                    b.HasOne("paskalON.Devices.Domain.Configs.GenericModbusDevices.Maps.GenericModbusMapConfig", "GenericModbusMapConfig")
                        .WithMany()
                        .HasForeignKey("GenericModbusMapConfigId");

                    b.HasOne("paskalON.Devices.Domain.Configs.GenericModbusDevices.Maps.GenericModbusCoilPointConfig", "OpenCommandCoil")
                        .WithMany()
                        .HasForeignKey("OpenCommandCoilId");

                    b.HasOne("paskalON.Devices.Domain.Configs.GenericModbusDevices.Maps.GenericModbusHoldingRegisterConfig", "OpenCommand")
                        .WithMany()
                        .HasForeignKey("OpenCommandId")
                        .HasConstraintName("FK_CircuitBreakerDeviceConfig_GenericModbusHoldingRegisterCon~2");

                    b.HasOne("paskalON.Devices.Domain.Configs.GenericModbusDevices.Maps.GenericModbusHoldingRegisterConfig", "ResetTrip")
                        .WithMany()
                        .HasForeignKey("ResetTripId")
                        .HasConstraintName("FK_CircuitBreakerDeviceConfig_GenericModbusHoldingRegisterCon~3");

                    b.HasOne("paskalON.Devices.Domain.Configs.GenericModbusDevices.Maps.GenericModbusHoldingRegisterConfig", "SettingsGroupCommand")
                        .WithMany()
                        .HasForeignKey("SettingsGroupCommandId")
                        .HasConstraintName("FK_CircuitBreakerDeviceConfig_GenericModbusHoldingRegisterCon~4");

                    b.HasOne("paskalON.Devices.Domain.Configs.GenericModbusDevices.Maps.GenericModbusHoldingRegisterConfig", "SettingsGroupState")
                        .WithMany()
                        .HasForeignKey("SettingsGroupStateId")
                        .HasConstraintName("FK_CircuitBreakerDeviceConfig_GenericModbusHoldingRegisterCon~5");

                    b.HasOne("paskalON.Devices.Domain.Configs.GenericModbusDevices.Maps.GenericModbusHoldingRegisterConfig", "SynchronousVoltage")
                        .WithMany()
                        .HasForeignKey("SynchronousVoltageId")
                        .HasConstraintName("FK_CircuitBreakerDeviceConfig_GenericModbusHoldingRegisterCon~6");

                    b.HasOne("paskalON.Devices.Domain.Configs.GenericModbusDevices.Maps.GenericModbusHoldingRegisterConfig", "TripState")
                        .WithMany()
                        .HasForeignKey("TripStateId")
                        .HasConstraintName("FK_CircuitBreakerDeviceConfig_GenericModbusHoldingRegisterCon~7");

                    b.Navigation("BreakerStateRegister");

                    b.Navigation("CloseCommand");

                    b.Navigation("CloseCommandCoil");

                    b.Navigation("GenericModbusMapConfig");

                    b.Navigation("OpenCommand");

                    b.Navigation("OpenCommandCoil");

                    b.Navigation("ResetTrip");

                    b.Navigation("SettingsGroupCommand");

                    b.Navigation("SettingsGroupState");

                    b.Navigation("SynchronousVoltage");

                    b.Navigation("TripState");
                });

            modelBuilder.Entity("paskalON.Devices.Domain.Configs.GenericModbusDevices.GenericModbusDeviceConfig", b =>
                {
                    b.HasOne("paskalON.Devices.Domain.Configs.GenericModbusDevices.Maps.GenericModbusMapConfig", "GenericModbusMapConfig")
                        .WithMany()
                        .HasForeignKey("GenericModbusMapConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GenericModbusMapConfig");
                });

            modelBuilder.Entity("paskalON.Devices.Domain.Configs.GenericModbusDevices.Maps.GenericModbusCoilPointConfig", b =>
                {
                    b.HasOne("paskalON.Devices.Domain.Configs.GenericModbusDevices.Maps.GenericModbusMapConfig", "GenericModbusMapConfig")
                        .WithMany("Coils")
                        .HasForeignKey("GenericModbusMapConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GenericModbusMapConfig");
                });

            modelBuilder.Entity("paskalON.Devices.Domain.Configs.GenericModbusDevices.Maps.GenericModbusDiscreteInputPointConfig", b =>
                {
                    b.HasOne("paskalON.Devices.Domain.Configs.GenericModbusDevices.Maps.GenericModbusMapConfig", "GenericModbusMapConfig")
                        .WithMany("DiscreteInputs")
                        .HasForeignKey("GenericModbusMapConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GenericModbusMapConfig");
                });

            modelBuilder.Entity("paskalON.Devices.Domain.Configs.GenericModbusDevices.Maps.GenericModbusHoldingRegisterConfig", b =>
                {
                    b.HasOne("paskalON.Devices.Domain.Configs.GenericModbusDevices.Maps.GenericModbusMapConfig", "GenericModbusMapConfig")
                        .WithMany("HoldingRegisters")
                        .HasForeignKey("GenericModbusMapConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GenericModbusMapConfig");
                });

            modelBuilder.Entity("paskalON.Devices.Domain.Configs.GenericModbusDevices.Maps.GenericModbusInputRegisterConfig", b =>
                {
                    b.HasOne("paskalON.Devices.Domain.Configs.GenericModbusDevices.Maps.GenericModbusMapConfig", "GenericModbusMapConfig")
                        .WithMany("InputRegisters")
                        .HasForeignKey("GenericModbusMapConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GenericModbusMapConfig");
                });

            modelBuilder.Entity("paskalON.Devices.Domain.Configs.Meters.PowerMeters.PowerMeterBaseConfig", b =>
                {
                    b.HasOne("paskalON.Devices.Domain.Configs.C37Config", "C37Config")
                        .WithMany()
                        .HasForeignKey("C37ConfigId");

                    b.HasOne("paskalON.Devices.Domain.Configs.ModbusConfig", "ModbusConfig")
                        .WithMany()
                        .HasForeignKey("ModbusConfigId");

                    b.HasOne("paskalON.Devices.Domain.Configs.Meters.PowerMeters.PowerMeterDeviceConfig", "PowerMeterDeviceConfig")
                        .WithMany()
                        .HasForeignKey("PowerMeterDeviceConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("paskalON.Devices.Domain.Configs.Meters.PowerMeters.PowerMeterBaseConfig", "RedundantPowerMeterConfig")
                        .WithMany()
                        .HasForeignKey("RedundantPowerMeterConfigId");

                    b.Navigation("C37Config");

                    b.Navigation("ModbusConfig");

                    b.Navigation("PowerMeterDeviceConfig");

                    b.Navigation("RedundantPowerMeterConfig");
                });

            modelBuilder.Entity("paskalON.Devices.Domain.Configs.Meters.PowerMeters.PowerMeterDeviceConfig", b =>
                {
                    b.HasOne("paskalON.Devices.Domain.Configs.Meters.PowerMeters.PowerMeterMapC37Config", "PowerMeterMapC37Config")
                        .WithMany()
                        .HasForeignKey("PowerMeterMapC37ConfigId");

                    b.HasOne("paskalON.Devices.Domain.Configs.Meters.PowerMeters.PowerMeterMapModbusConfig", "PowerMeterMapModbusConfig")
                        .WithMany()
                        .HasForeignKey("PowerMeterMapModbusConfigId");

                    b.Navigation("PowerMeterMapC37Config");

                    b.Navigation("PowerMeterMapModbusConfig");
                });

            modelBuilder.Entity("paskalON.Devices.Domain.Configs.Meters.PowerMeters.PowerMeterMapModbusConfig", b =>
                {
                    b.HasOne("paskalON.Communication.Protocols.Modbus.Configurations.ModbusRegisterMapEntryConfig", "ActivePowerAMap")
                        .WithMany()
                        .HasForeignKey("ActivePowerAMapModbusRegisterMapEntryConfigId");

                    b.HasOne("paskalON.Communication.Protocols.Modbus.Configurations.ModbusRegisterMapEntryConfig", "ActivePowerBMap")
                        .WithMany()
                        .HasForeignKey("ActivePowerBMapModbusRegisterMapEntryConfigId")
                        .HasConstraintName("FK_PowerMeterMapModbusConfig_ModbusRegisterMapEntryConfig_Act~1");

                    b.HasOne("paskalON.Communication.Protocols.Modbus.Configurations.ModbusRegisterMapEntryConfig", "ActivePowerCMap")
                        .WithMany()
                        .HasForeignKey("ActivePowerCMapModbusRegisterMapEntryConfigId")
                        .HasConstraintName("FK_PowerMeterMapModbusConfig_ModbusRegisterMapEntryConfig_Act~2");

                    b.HasOne("paskalON.Communication.Protocols.Modbus.Configurations.ModbusRegisterMapEntryConfig", "ActivePowerMap")
                        .WithMany()
                        .HasForeignKey("ActivePowerMapModbusRegisterMapEntryConfigId")
                        .HasConstraintName("FK_PowerMeterMapModbusConfig_ModbusRegisterMapEntryConfig_Act~3");

                    b.HasOne("paskalON.Communication.Protocols.Modbus.Configurations.ModbusRegisterMapEntryConfig", "ApparentPowerMap")
                        .WithMany()
                        .HasForeignKey("ApparentPowerMapModbusRegisterMapEntryConfigId");

                    b.HasOne("paskalON.Communication.Protocols.Modbus.Configurations.ModbusRegisterMapEntryConfig", "CurrentAMap")
                        .WithMany()
                        .HasForeignKey("CurrentAMapModbusRegisterMapEntryConfigId");

                    b.HasOne("paskalON.Communication.Protocols.Modbus.Configurations.ModbusRegisterMapEntryConfig", "CurrentBMap")
                        .WithMany()
                        .HasForeignKey("CurrentBMapModbusRegisterMapEntryConfigId")
                        .HasConstraintName("FK_PowerMeterMapModbusConfig_ModbusRegisterMapEntryConfig_Cur~1");

                    b.HasOne("paskalON.Communication.Protocols.Modbus.Configurations.ModbusRegisterMapEntryConfig", "CurrentCMap")
                        .WithMany()
                        .HasForeignKey("CurrentCMapModbusRegisterMapEntryConfigId")
                        .HasConstraintName("FK_PowerMeterMapModbusConfig_ModbusRegisterMapEntryConfig_Cur~2");

                    b.HasOne("paskalON.Communication.Protocols.Modbus.Configurations.ModbusRegisterMapEntryConfig", "EnergyDeliveredMap")
                        .WithMany()
                        .HasForeignKey("EnergyDeliveredMapModbusRegisterMapEntryConfigId");

                    b.HasOne("paskalON.Communication.Protocols.Modbus.Configurations.ModbusRegisterMapEntryConfig", "EnergyReceivedMap")
                        .WithMany()
                        .HasForeignKey("EnergyReceivedMapModbusRegisterMapEntryConfigId")
                        .HasConstraintName("FK_PowerMeterMapModbusConfig_ModbusRegisterMapEntryConfig_Ene~1");

                    b.HasOne("paskalON.Communication.Protocols.Modbus.Configurations.ModbusRegisterMapEntryConfig", "FrequencyMap")
                        .WithMany()
                        .HasForeignKey("FrequencyMapModbusRegisterMapEntryConfigId");

                    b.HasOne("paskalON.Communication.Protocols.Modbus.Configurations.ModbusRegisterMapEntryConfig", "PowerFactorMap")
                        .WithMany()
                        .HasForeignKey("PowerFactorMapModbusRegisterMapEntryConfigId");

                    b.HasOne("paskalON.Communication.Protocols.Modbus.Configurations.ModbusRegisterMapEntryConfig", "ReactiveEnergyDeliveredMap")
                        .WithMany()
                        .HasForeignKey("ReactiveEnergyDeliveredMapModbusRegisterMapEntryConfigId");

                    b.HasOne("paskalON.Communication.Protocols.Modbus.Configurations.ModbusRegisterMapEntryConfig", "ReactiveEnergyReceivedMap")
                        .WithMany()
                        .HasForeignKey("ReactiveEnergyReceivedMapModbusRegisterMapEntryConfigId")
                        .HasConstraintName("FK_PowerMeterMapModbusConfig_ModbusRegisterMapEntryConfig_Rea~1");

                    b.HasOne("paskalON.Communication.Protocols.Modbus.Configurations.ModbusRegisterMapEntryConfig", "ReactivePowerAMap")
                        .WithMany()
                        .HasForeignKey("ReactivePowerAMapModbusRegisterMapEntryConfigId")
                        .HasConstraintName("FK_PowerMeterMapModbusConfig_ModbusRegisterMapEntryConfig_Rea~2");

                    b.HasOne("paskalON.Communication.Protocols.Modbus.Configurations.ModbusRegisterMapEntryConfig", "ReactivePowerBMap")
                        .WithMany()
                        .HasForeignKey("ReactivePowerBMapModbusRegisterMapEntryConfigId")
                        .HasConstraintName("FK_PowerMeterMapModbusConfig_ModbusRegisterMapEntryConfig_Rea~3");

                    b.HasOne("paskalON.Communication.Protocols.Modbus.Configurations.ModbusRegisterMapEntryConfig", "ReactivePowerCMap")
                        .WithMany()
                        .HasForeignKey("ReactivePowerCMapModbusRegisterMapEntryConfigId")
                        .HasConstraintName("FK_PowerMeterMapModbusConfig_ModbusRegisterMapEntryConfig_Rea~4");

                    b.HasOne("paskalON.Communication.Protocols.Modbus.Configurations.ModbusRegisterMapEntryConfig", "ReactivePowerMap")
                        .WithMany()
                        .HasForeignKey("ReactivePowerMapModbusRegisterMapEntryConfigId")
                        .HasConstraintName("FK_PowerMeterMapModbusConfig_ModbusRegisterMapEntryConfig_Rea~5");

                    b.HasOne("paskalON.Communication.Protocols.Modbus.Configurations.ModbusRegisterMapEntryConfig", "VoltageAMap")
                        .WithMany()
                        .HasForeignKey("VoltageAMapModbusRegisterMapEntryConfigId");

                    b.HasOne("paskalON.Communication.Protocols.Modbus.Configurations.ModbusRegisterMapEntryConfig", "VoltageBMap")
                        .WithMany()
                        .HasForeignKey("VoltageBMapModbusRegisterMapEntryConfigId")
                        .HasConstraintName("FK_PowerMeterMapModbusConfig_ModbusRegisterMapEntryConfig_Vol~1");

                    b.HasOne("paskalON.Communication.Protocols.Modbus.Configurations.ModbusRegisterMapEntryConfig", "VoltageCMap")
                        .WithMany()
                        .HasForeignKey("VoltageCMapModbusRegisterMapEntryConfigId")
                        .HasConstraintName("FK_PowerMeterMapModbusConfig_ModbusRegisterMapEntryConfig_Vol~2");

                    b.HasOne("paskalON.Communication.Protocols.Modbus.Configurations.ModbusRegisterMapEntryConfig", "VoltageLLAvgMap")
                        .WithMany()
                        .HasForeignKey("VoltageLLAvgMapModbusRegisterMapEntryConfigId")
                        .HasConstraintName("FK_PowerMeterMapModbusConfig_ModbusRegisterMapEntryConfig_Vol~3");

                    b.Navigation("ActivePowerAMap");

                    b.Navigation("ActivePowerBMap");

                    b.Navigation("ActivePowerCMap");

                    b.Navigation("ActivePowerMap");

                    b.Navigation("ApparentPowerMap");

                    b.Navigation("CurrentAMap");

                    b.Navigation("CurrentBMap");

                    b.Navigation("CurrentCMap");

                    b.Navigation("EnergyDeliveredMap");

                    b.Navigation("EnergyReceivedMap");

                    b.Navigation("FrequencyMap");

                    b.Navigation("PowerFactorMap");

                    b.Navigation("ReactiveEnergyDeliveredMap");

                    b.Navigation("ReactiveEnergyReceivedMap");

                    b.Navigation("ReactivePowerAMap");

                    b.Navigation("ReactivePowerBMap");

                    b.Navigation("ReactivePowerCMap");

                    b.Navigation("ReactivePowerMap");

                    b.Navigation("VoltageAMap");

                    b.Navigation("VoltageBMap");

                    b.Navigation("VoltageCMap");

                    b.Navigation("VoltageLLAvgMap");
                });

            modelBuilder.Entity("paskalON.Devices.Domain.Configs.ModbusConfig", b =>
                {
                    b.HasOne("paskalON.Devices.Domain.Configs.ModbusConnectionConfig", "ModbusConnectionConfig")
                        .WithMany()
                        .HasForeignKey("ModbusConnectionConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ModbusConnectionConfig");
                });

            modelBuilder.Entity("paskalON.Devices.Domain.Configs.PowerConversionSystems.PowerConversionSystemConfig", b =>
                {
                    b.HasOne("paskalON.Devices.Domain.Configs.Ders.DerUnitConfig", "DerUnitConfig")
                        .WithOne("PowerConversionSystemConfig")
                        .HasForeignKey("paskalON.Devices.Domain.Configs.PowerConversionSystems.PowerConversionSystemConfig", "DerUnitConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("paskalON.Devices.Domain.Configs.ModbusConfig", "ModbusConfig")
                        .WithMany()
                        .HasForeignKey("ModbusConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("paskalON.Devices.Domain.Configs.PowerConversionSystems.PowerConversionSystemDeviceConfig", "PowerConversionSystemDeviceConfig")
                        .WithMany()
                        .HasForeignKey("PowerConversionSystemDeviceConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DerUnitConfig");

                    b.Navigation("ModbusConfig");

                    b.Navigation("PowerConversionSystemDeviceConfig");
                });

            modelBuilder.Entity("paskalON.Devices.Domain.Configs.Meters.PowerMeters.AuxiliaryPowerMeterConfig", b =>
                {
                    b.HasOne("paskalON.Devices.Domain.Configs.Ders.DerConfig", "DerConfig")
                        .WithMany("AuxiliaryPowerMeterConfigs")
                        .HasForeignKey("DerConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DerConfig");
                });

            modelBuilder.Entity("paskalON.Devices.Domain.Configs.Meters.PowerMeters.CircuitPowerMeterConfig", b =>
                {
                    b.HasOne("paskalON.Devices.Domain.Configs.Ders.DerCircuitConfig", "DerCircuitConfig")
                        .WithOne("CircuitPowerMeterConfig")
                        .HasForeignKey("paskalON.Devices.Domain.Configs.Meters.PowerMeters.CircuitPowerMeterConfig", "DerCircuitConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DerCircuitConfig");
                });

            modelBuilder.Entity("paskalON.Devices.Domain.Configs.Meters.PowerMeters.ExternalPowerMeterConfig", b =>
                {
                    b.HasOne("paskalON.Devices.Domain.Configs.Ders.DerConfig", "DerConfig")
                        .WithMany("ExternalPowerMeterConfigs")
                        .HasForeignKey("DerConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DerConfig");
                });

            modelBuilder.Entity("paskalON.Devices.Domain.Configs.Meters.PowerMeters.SystemPowerMeterConfig", b =>
                {
                    b.HasOne("paskalON.Devices.Domain.Configs.Ders.DerConfig", "DerConfig")
                        .WithMany("SystemPowerMeterConfigs")
                        .HasForeignKey("DerConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DerConfig");
                });

            modelBuilder.Entity("paskalON.Devices.Domain.Configs.GenericModbusDevices.AutomaticTransferSwitchConfig", b =>
                {
                    b.HasOne("paskalON.Devices.Domain.Configs.GenericModbusDevices.AutomaticTransferSwitchDeviceConfig", "AutomaticTransferSwitchDeviceConfig")
                        .WithMany()
                        .HasForeignKey("AutomaticTransferSwitchDeviceConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("paskalON.Devices.Domain.Configs.Ders.DerConfig", "DerConfig")
                        .WithMany("AutomaticTransferSwitchConfigs")
                        .HasForeignKey("DerConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AutomaticTransferSwitchDeviceConfig");

                    b.Navigation("DerConfig");
                });

            modelBuilder.Entity("paskalON.Devices.Domain.Configs.GenericModbusDevices.CircuitBreakerConfig", b =>
                {
                    b.HasOne("paskalON.Devices.Domain.Configs.GenericModbusDevices.CircuitBreakerDeviceConfig", "CircuitBreakerDeviceConfig")
                        .WithMany()
                        .HasForeignKey("CircuitBreakerDeviceConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("paskalON.Devices.Domain.Configs.Ders.DerCircuitConfig", "DerCircuitConfig")
                        .WithOne("CircuitBreakerConfig")
                        .HasForeignKey("paskalON.Devices.Domain.Configs.GenericModbusDevices.CircuitBreakerConfig", "DerCircuitConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CircuitBreakerDeviceConfig");

                    b.Navigation("DerCircuitConfig");
                });

            modelBuilder.Entity("paskalON.Devices.Domain.Configs.GenericModbusDevices.GenericModbusConfig", b =>
                {
                    b.HasOne("paskalON.Devices.Domain.Configs.Ders.DerConfig", "DerConfig")
                        .WithMany("GenericModbusConfigs")
                        .HasForeignKey("DerConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("paskalON.Devices.Domain.Configs.GenericModbusDevices.GenericModbusDeviceConfig", "GenericModbusDeviceConfig")
                        .WithMany()
                        .HasForeignKey("GenericModbusDeviceConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DerConfig");

                    b.Navigation("GenericModbusDeviceConfig");
                });

            modelBuilder.Entity("paskalON.Devices.Domain.Configs.GenericModbusDevices.GenericModbusUnitConfig", b =>
                {
                    b.HasOne("paskalON.Devices.Domain.Configs.Ders.DerUnitConfig", "DerUnitConfig")
                        .WithOne("GenericModbusUnitConfig")
                        .HasForeignKey("paskalON.Devices.Domain.Configs.GenericModbusDevices.GenericModbusUnitConfig", "DerUnitConfigId");

                    b.HasOne("paskalON.Devices.Domain.Configs.GenericModbusDevices.GenericModbusDeviceConfig", "GenericModbusDeviceConfig")
                        .WithMany()
                        .HasForeignKey("GenericModbusDeviceConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DerUnitConfig");

                    b.Navigation("GenericModbusDeviceConfig");
                });

            modelBuilder.Entity("paskalON.Devices.Domain.Configs.Ders.DerCircuitConfig", b =>
                {
                    b.Navigation("CircuitBreakerConfig");

                    b.Navigation("CircuitPowerMeterConfig");

                    b.Navigation("DerUnitConfigs");
                });

            modelBuilder.Entity("paskalON.Devices.Domain.Configs.Ders.DerConfig", b =>
                {
                    b.Navigation("AutomaticTransferSwitchConfigs");

                    b.Navigation("AuxiliaryPowerMeterConfigs");

                    b.Navigation("DerGroupConfigs");

                    b.Navigation("ExternalPowerMeterConfigs");

                    b.Navigation("GenericModbusConfigs");

                    b.Navigation("SystemPowerMeterConfigs");
                });

            modelBuilder.Entity("paskalON.Devices.Domain.Configs.Ders.DerGroupConfig", b =>
                {
                    b.Navigation("DerCircuits");
                });

            modelBuilder.Entity("paskalON.Devices.Domain.Configs.Ders.DerUnitConfig", b =>
                {
                    b.Navigation("DerContainerConfig");

                    b.Navigation("GenericModbusUnitConfig");

                    b.Navigation("PowerConversionSystemConfig")
                        .IsRequired();
                });

            modelBuilder.Entity("paskalON.Devices.Domain.Configs.EnergyStorages.Batteries.BatteryBankDeviceConfig", b =>
                {
                    b.Navigation("Customs");
                });

            modelBuilder.Entity("paskalON.Devices.Domain.Configs.GenericModbusDevices.Maps.GenericModbusMapConfig", b =>
                {
                    b.Navigation("Coils");

                    b.Navigation("DiscreteInputs");

                    b.Navigation("HoldingRegisters");

                    b.Navigation("InputRegisters");
                });

            modelBuilder.Entity("paskalON.Devices.Domain.Configs.Meters.PowerMeters.PowerMeterMapModbusConfig", b =>
                {
                    b.Navigation("PollingRange");
                });

            modelBuilder.Entity("paskalON.Devices.Domain.Configs.PowerConversionSystems.PowerConversionSystemDeviceConfig", b =>
                {
                    b.Navigation("Customs");
                });

            modelBuilder.Entity("paskalON.Devices.Domain.Configs.Ders.DerBatteryStorageUnitConfig", b =>
                {
                    b.Navigation("BatteryBankConfigs");
                });

            modelBuilder.Entity("paskalON.Devices.Domain.Configs.Ders.DerSolarUnitConfig", b =>
                {
                    b.Navigation("SolarPanelConfig")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
