{
 "title": "Loki Dashboard",
 "time": { "from": "now-5h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "service_name",
    "label": "Service Names",
    "query": {}
   },
   { "name": "searchable_pattern", "label": "Search (case insensitive)" },
   { "name": "datasource", "label": "Datasource", "query": "loki" }
  ]
 },
 "panels": [
  { "title": "Statistics & Critical Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Count of logs over time range. $searchable_pattern",
   "type": "stat",
   "description": "Total Count of logs over time range including the search pattern: $searchable_pattern",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({service_name=~\"$service_name\"} |~ \"(?i)$searchable_pattern\" [$__interval]))"
    }
   ]
  },
  {
   "title": "Total Count of error over time range. $searchable_pattern",
   "type": "stat",
   "description": "Total Count of error over time range including the search pattern: $searchable_pattern",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({service_name=~\"$service_name\"} | severity_text=~\"Error\" [$__interval]))"
    }
   ]
  },
  {
   "title": "Total Count of critical over time range. $searchable_pattern",
   "type": "stat",
   "description": "Total Count of critical over time range including the search pattern: $searchable_pattern",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({service_name=~\"$service_name\"} | severity_text=~\"Critical\" [$__interval]))"
    }
   ]
  },
  {
   "title": "Historical count of logs over time range. $searchable_pattern",
   "type": "timeseries",
   "description": "Historical count of logs over time range including the search pattern: $searchable_pattern",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({service_name=~\"$service_name\"} |~ \"(?i)$searchable_pattern\" [$__interval]))"
    }
   ]
  },
  {
   "title": "Last critical logs",
   "type": "logs",
   "gridPos": { "h": 14, "w": 18, "x": 0, "y": 12 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=~\"$service_name\"} |~ `(?i)$searchable_pattern` | severity_text = `Critical`",
     "maxLines": 50
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Last logs",
   "type": "logs",
   "description": "Last logs is a like 'tail -f' in a real time",
   "gridPos": { "h": 17, "w": 18, "x": 0, "y": 27 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=~\"$service_name\"} |~ \"(?i)$searchable_pattern\""
    }
   ]
  }
 ]
}